### ISSUE TITLE
include stand age in weighting function? 

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#100]
I'm listening to an AGU talk by John Battles- "Detecting and accounting for allometric variation in trees…"

Allometries vary by stand age, with equations based on young stands predicting more biomass than those based on old stands (makes sense).

@gonzalezeb is including stand age in our equations data table. @cpiponiot, are you planning to include this in the weighting function?

**Comment by gonzalezeb** [comment]
We did not include stand age as the data is very limited and not standardized..maybe to include in a future version of alldb.
