### ISSUE TITLE
problem with data.r

### ISSUE THREAD

**Issue by gonzalezeb** [forestgeo/allodb#101]
Hi @maurolepore , 
I am having troubles when trying run [this scrip](https://github.com/forestgeo/allodb/blob/master/data-raw/data.R) and cannot find a solution online. 

I get this error when running line 9.
> db_nms <- path_ext_remove(path_file(dir_ls(path_db)))
Error: [ENOENT] Failed to search directory 'data-raw/csv_database': no such file or directory.

Any ideas? Thank you very much for your help!!

**Comment by maurolepore** [comment]
Hi @gonzalezeb,

Your error suggests that the directory "data-raw/csv_database" can't be found from your working directory.  Is your working directory set correctly, to the root of the allodb project?


I can't reproduce your problem. I cloned the master branch from GitHub and run the file with no error. Here is a [reprex](https://reprex.tidyverse.org/) of the relevant piece of code:

``` r
library(fs)

path_db <- "data-raw/csv_database"
db_nms <- path_ext_remove(path_file(dir_ls(path_db)))
db_nms
#>  [1] "equations"               "equations_metadata"     
#>  [3] "missing_values_metadata" "references"             
#>  [5] "references_metadata"     "sitespecies"            
#>  [7] "sitespecies_metadata"    "sites_info"             
#>  [9] "wsg"                     "wsg_metadata"
```

<sup>Created on 2020-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by maurolepore** [comment]
You may want to run `here::here()` to confirm your working directory is the one you think. For example, here is the same code with the additional call to `here::here()`.

``` r
library(fs)

here::here()
#> [1] "C:/Users/Mauro/Desktop/allodb"
path_db <- "data-raw/csv_database"
db_nms <- path_ext_remove(path_file(dir_ls(path_db)))
db_nms
#>  [1] "equations"               "equations_metadata"     
#>  [3] "missing_values_metadata" "references"             
#>  [5] "references_metadata"     "sitespecies"            
#>  [7] "sitespecies_metadata"    "sites_info"             
#>  [9] "wsg"                     "wsg_metadata"
```

<sup>Created on 2020-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by gonzalezeb** [comment]
Thanks Mauro, I saw the error. My working directory was allodb/data-raw,
I added an extra line in the script to remind myself. 
Hope everything is going well!
