### ISSUE TITLE
Problem with equation dc04c7

### ISSUE THREAD

**Issue by cpiponiot** [forestgeo/allodb#102]
@gonzalezeb  just to report that equation dc04c7 (from Jenkins et al. 2004) in the equation table has weird coefficients (agb = exp(-3463.8+1083.9*log(dbh)), which basically results in AGB=0 when dbh < 20 and AGB= infinity when dbh > 30...

**Comment by gonzalezeb** [comment]
Thanks Camille for catching that, I fixed both equations for  Thuja plicata. They actually were built using drc (diameter at root collar) so we needed to convert dbh to drc. Equation dc04c7 actually is : -3463.8+1083.9*(dbh)
