### ISSUE TITLE
sourcing + documentation of get_biomass?

### ISSUE THREAD

**Issue by ValentineHerr** [forestgeo/allodb#103]
I am starting to learn how to use allodb.

It would be nice to have `get_biomass()` directly sourced when running `library(allodb)` and to have have a help file show up when typing `?get_biomass`. Currently it does not work for 2 reasons:
1. get_biomass is not exported in NAMESPACE (so doing `library(allodb)` does not import function `get_biomass()`
2. there is no documentation for `get_biomass(0` in /man/

There might be good reasons for that. You can just ignore this issue if that is the case.I am just telling you from a user point of view.

**Comment by gonzalezeb** [comment]
Thanks Valentine. Closing issue because `?get_biomass` is working now.
