### ISSUE TITLE
some negative AGB estimates within DBH range for 3 equations

### ISSUE THREAD

**Issue by cpiponiot** [forestgeo/allodb#106]
There are still 3 equations that predict negative values inside their dbh range (mostly for small dbhs): 

- ref_id: jenkins_2004_cdod, equation_id: 9f4b7d, equation_taxa: Picea engelmannii

- ref_id: singh_1984_befs, equation_id: a5de78, equation_taxa: Pinus banksiana

- ref_id: yarie_2007_abef, equation_id: 686376, equation_taxa: Betula neoalaskana 

I'm raising this issue because I realized that some AGB predictions were negative for some species (mostly conifers) at small dbhs (< 5 cm), something we definitely want to avoid. What should we do with those equations? Should we remove them completely, or change their dbh range in the equation table to get rid of negative values?

**Comment by teixeirak** [comment]
I'd change the DBH range (assuming equations are known to be correctly transcribed), although I'm not sure exactly how to determine where. 

Related to this (but not replacing the removal of negative values), I wonder if we should apply a more severe de-weighting to equations approaching the edge of their DBH range? (That is, keep the gradual slope of transition between allometries, but start the de-weighting further in from the DBH limits.

**Comment by gonzalezeb** [comment]
Sorry, I din't see this issue before:
for eq 686376, Betula neoalaskana, I went to the original pub and choose a different model, the new equations works now for the dbh range.

for eq  a5de78, Pinus banksiana, I changed the minimun dbh to 10 cm, as the majority of stems for the sampled Jack pine were above 10cm

for the other equation, I am waiting for the library to send me the original pub, sometimes Jenkings values are incorrect.

**Comment by gonzalezeb** [comment]
The original pub for eq 9f4b7d, was correct. We changed minimum dbh to 10 cm (although pub says it measured dbh down to 3.6 cm).
