### ISSUE TITLE
non monotonous agb

### ISSUE THREAD

**Issue by ValentineHerr** [forestgeo/allodb#107]
@cpiponiot and @gonzalezeb,

I found a case where agb is not monotonous (it decreases while dbh increases):

![image](https://user-images.githubusercontent.com/19673377/80382566-6b87d480-8870-11ea-9a4a-747731fa0b3f.png)
 

I'll let you know if I found other cases.

**Comment by ValentineHerr** [comment]
Fortunately it seems to be only for Pinus strobus (at least in the set of species I am working on)

**Comment by teixeirak** [comment]
Here's @cpiponiot's figure showing the function for Pinus strobus: [Pinus_strobus.pdf](https://github.com/forestgeo/allodb/blob/master/tests/graphs/scbi/Pinus_strobus.pdf). Note that there's a missing portion on the log-scale graph, presumably because of negative values.

![image](https://user-images.githubusercontent.com/6355854/80383344-755e0780-8871-11ea-9709-98e65ed1ab79.png)

**Comment by teixeirak** [comment]
Solving issue #106 should solve this problem.

**Comment by teixeirak** [comment]
@gonzalezeb , @cpiponiot, From a review of the thumbnails of the test figures that are currently in the repo, here's what I've found that needs fixing:
- [ ] almost all conifers have issues at dbh<10. There are some exceptions (e.g., unk_conifer at Traunstein).
- [ ] There are some outdated graphs for species that are no longer in the list. The solution is to delete all plots before generating the next set

I won't bother reviewing any more right now, as I think we have a pretty clear sense of what's going on. Once we have a new set with fixed conifer equation and old plots deleted, I'll be happy to flip through the thumbnails again.

Below is my complete list (by site, all species listed have issues).

---
Changbaishan: 
Abies
Pinus korainensis

Gutianshan:
Pinus_massoniana

Harvard forest:
Picea
Pinus
Tsuga

Michigan big woods:
Quercus (not terrible, but has some sharp transitions) – probably solved and just needs to be re-run

Niobara:
Pinus ponderosa

Ordway Swisher:
Pinus palustris

SCBI:
Pinus

Scotty:
Larix laricina
Picea
Pinus

SERC:
Pinus

Speulderbos:
Larix kaempferi
Larix spp. is a bit funny
Pinus
Pseudotsuga
Tsuga

Traunstein:
Abies
Larix
Picea
Pinus
Pseudotsuga
(unk_conifer is fine)

**Sites where all species look good:**
Lilly Dickey
Tiantongshan
Tyson
UCSC

**Comment by gonzalezeb** [comment]
There are no non-monotonous allometries in allodb anymore. It seems that the issue was with equations with non-minimum dbh values (NRA, i.e. bohn_2014, eq 307ec5). We also tested equations to determine when a negative `agb` resulted below a minimum dbh and changed accordingly.
@ValentineHerr lets us know if you find other issues.

**Comment by teixeirak** [comment]
Hooray! Thank you!

**Comment by ValentineHerr** [comment]
I am still having non-monotonous issues... here is the list of species and an example:

![image](https://user-images.githubusercontent.com/19673377/85305321-e89f8680-b47a-11ea-9db1-c065d23a485c.png)


```
get_biomass(dbh = c(0.726, 1.3, 1.995),
            genus = "Picea", 
            species = "abies", 
            coords = c(-72.1755 , 42.5388))
```

**Comment by gonzalezeb** [comment]
I get these values when I run it, no negative results..
> library(allodb)
> get_biomass(dbh = c(0.726, 1.3, 1.995),
genus = "Picea", 
species = "abies", 
coords = c(-72.1755 , 42.5388))
[1] 0.04041169 0.14762693 0.42062280

**Comment by ValentineHerr** [comment]
hmm strange... let me try it again

**Comment by ValentineHerr** [comment]
@gonzalezeb do you have the latest version of allodb? (run `remotes::install_github("forestgeo/allodb")` before trying your code above again)

I get ` [1] 1.662471 1.555114 1.655411`

**Comment by gonzalezeb** [comment]
@ValentineHerr 
If I run it from remotes and I get the same values as before ([1] 0.04041169 0.14762693 0.42062280).
but if I run it from the repository I get the same values you got. 
Maybe @cpiponiot has some idea why this discrepancy. 

But the question is : Are you still getting neg values?

**Comment by ValentineHerr** [comment]
weird...


>But the question is : Are you still getting neg values?

Yes, @cpiponiot should know from issue #109

**Comment by cpiponiot** [comment]
Yes, I changed the weighting function recently to make sure the right weights are attributed to each equation, but I haven't finished updating the function completely and now we get negative values. I'll investigate this issue today, and I'll check that we get monotonous and strictly positive allometries.

**Comment by rudeboybert** [comment]
I just finished reading your manuscript draft. I got so excited by it I jumped right into the code!

A heads up that I found a few more species with non-monotonic agb functions. They are in the `scbi_stem1` dataset which was in the `?get_biomass()` help file: Rosa multiflora, Rubus allegheniensis, Rubus pensilvanicus, Rubus phoenicolasius, Viburnum prunifolium.

Note that I'm using `allodb_0.0.0.9005` which I just installed via `remotes::install_github("forestgeo/allodb")`

``` r
library(tidyverse)
library(allodb)
data(scbi_stem1)

scbi_stem1 <- scbi_stem1 %>%
  as_tibble() %>%
  mutate(
    # Using same example as in ?get_biomass
    biomass = get_biomass(
      dbh = dbh,
      genus = genus,
      species = species,
      coords = c(-78.2, 38.9)
    ),
    # Create sp variable
    sp = str_c(genus, species, sep = " ")
  ) %>%
  # Limit to just non-monotonic sp (there may be others)
  filter(
    sp %in% c("Rosa multiflora", "Rubus allegheniensis", 
              "Rubus pensilvanicus", "Rubus phoenicolasius", 
              "Viburnum prunifolium")
  )

ggplot(scbi_stem1, aes(x = dbh, y = biomass)) +
  geom_point() +
  facet_wrap(~sp, scales = "free")
```

![](https://i.imgur.com/fII6SYP.png)

<sup>Created on 2020-07-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cpiponiot** [comment]
I looked into these examples from SCBI, and it seems that the non-monotonic behaviour is caused by equations with high weights (genus- or species-specific equations) that have different DBH ranges. 
For example, in the case of _Viburnum prunifolium_: 
![image](https://user-images.githubusercontent.com/20208665/88904816-de309380-d255-11ea-8615-796ed9204984.png)
the 2 equations with the highest weights for small dbhs predict different AGB values between their respective dbh ranges (0.28-1.59 cm and 5.5 - 31 cm dbh):
![image](https://user-images.githubusercontent.com/20208665/88905644-c86f9e00-d256-11ea-8dc7-26147abd8e68.png)

We could try to tweak the dbh-range weight function to have smoother transitions, but there's a tradeoff between smooth transitions and giving low weights to predictions outside of the equations' DBH range...

**Comment by gonzalezeb** [comment]
Ok, part of the problem (I think) is that I entered the dbh range in mm instead of cm for few species (i.e. for Viburmin sargentii).. 

I corrected the files, so if you running it again Camille, it should improve.

**Comment by cpiponiot** [comment]
Okay great I'll try it! That should indeed solve some of the inconsistency problems that we've been having for low DBH values.

**Comment by cpiponiot** [comment]
Good news, the changes you made to the DBH ranges solved the problem of non-monotonic allometries (at least in SCBI, I haven't checked other sites yet)!

**Comment by gonzalezeb** [comment]
@cpiponiot 
I checked all the species mentioned by Valentine above (June 22), and they seem to be working fine. What surprised me is that if I write a genus with a small letter then the agb result slightly change, see for example.

>get_biomass(dbh = c(0.726, 1.3, 1.9),
genus = "Abies", 
species = "alba", 
 coords = c(-72.1755 , 42.5388))
[1] 0.5675903 0.4155617 0.5124866`

> get_biomass(dbh = c(0.726, 1.3, 1.9),
genus = "abies", 
species = "alba", 
coords = c(-72.1755 , 42.5388))
[1] 0.2256897 0.4173885 0.7161265

Maybe we need to mention as a warning

**Comment by ValentineHerr** [comment]
I think I still have non-monotonous issues fort eh following sites-species combinations:

![image](https://user-images.githubusercontent.com/19673377/89302562-fe3acb00-d638-11ea-9019-50850b9a4b8c.png)

**Comment by cpiponiot** [comment]
> @cpiponiot
> I checked all the species mentioned by Valentine above (June 22), and they seem to be working fine. What surprised me is that if I write a genus with a small letter then the agb result slightly change, see for example.
> 
> > get_biomass(dbh = c(0.726, 1.3, 1.9),
> > genus = "Abies",
> > species = "alba",
> > coords = c(-72.1755 , 42.5388))
> > [1] 0.5675903 0.4155617 0.5124866`
> 
> > get_biomass(dbh = c(0.726, 1.3, 1.9),
> > genus = "abies",
> > species = "alba",
> > coords = c(-72.1755 , 42.5388))
> > [1] 0.2256897 0.4173885 0.7161265
> 
> Maybe we need to mention as a warning

It's probably just because the function doesn't recognize the genus if it's in lower cases, but that would be an easy fix within the function, I'll put it on my to-do list

**Comment by cpiponiot** [comment]
> I think I still have non-monotonous issues for the following sites-species combinations:

I'll check what's happening there

**Comment by gonzalezeb** [comment]
@ValentineHerr are you finding that the non-monotonous values are commonly in the small DBHs sizes? I tested all species you mentioned and they seem to be fine except Abies alba..see for example:

```
> get_biomass(dbh = c(0.726, 1.3, 1.9, 2, 10, 20, 100),
+             genus = "Abies",
+             species = "alba",
+             coords = c(-72.1755 , 42.5388))
[1]    0.5675903    0.4155617    0.5124866    0.5474221   22.2144618  124.3464851
[7] 7314.1336693
```

**Comment by cpiponiot** [comment]
> @cpiponiot
> I checked all the species mentioned by Valentine above (June 22), and they seem to be working fine. What surprised me is that if I write a genus with a small letter then the agb result slightly change, see for example.
> 
> > get_biomass(dbh = c(0.726, 1.3, 1.9),
> > genus = "Abies",
> > species = "alba",
> > coords = c(-72.1755 , 42.5388))
> > [1] 0.5675903 0.4155617 0.5124866`
> 
> > get_biomass(dbh = c(0.726, 1.3, 1.9),
> > genus = "abies",
> > species = "alba",
> > coords = c(-72.1755 , 42.5388))
> > [1] 0.2256897 0.4173885 0.7161265
> 
> Maybe we need to mention as a warning

![image](https://user-images.githubusercontent.com/20208665/89517711-670d7900-d7da-11ea-8ee7-9caa9e5cc336.png)

Problem solved

**Comment by cpiponiot** [comment]
I changed the get_biomass function quite a lot (especially the taxonomic weight part) and the problem with small DBHs seems to be solved BUT we now have some very weird patterns for large DBHs and I need to figure out what's happening there:

![image](https://user-images.githubusercontent.com/20208665/89524283-94f7bb00-d7e4-11ea-8058-9c33ae35b6c4.png)

**Comment by cpiponiot** [comment]
There is not more monotonicity problem for stems > 1cm dbh; for stems  < 1cm dbh however, for a small number of species, there is a little decrease in AGB (see graph below, note the log scale), but I don't think this is very worrying. My guess would be that this is caused by the handling of equations with infinite AGB predictions for stems around 1 mm dbh. 

![image](https://user-images.githubusercontent.com/20208665/90397254-debf8b80-e097-11ea-924f-4b6a90203626.png)

**Comment by teixeirak** [comment]
I'd agree that it's not too worrying, but we should probably put a warning of this somewhere in the documentation. @ValentineHerr, we probably want to exclude these species / size-range combinations from the tree-ring analysis.

**Comment by ValentineHerr** [comment]
Hmmm.. I am still having issues for larger DBH. But I believe it is due to an earlier problem that reappeared: agb calculation depends on the subset of the data. I'll double check after I restart my session, but for now, I get different agb results when I use `get_biomass` on a subset of my data.

**Comment by ValentineHerr** [comment]
never mind for that previous issue or inconsistent calculations. 
But I do have non-monotonous cases for larger DBHs:

![image](https://user-images.githubusercontent.com/19673377/90538708-e68d3780-e14c-11ea-96ac-9c57080105ed.png)
(broken lines are because I plot each coreID separately)
![image](https://user-images.githubusercontent.com/19673377/90538822-12a8b880-e14d-11ea-84c1-32f401cddfe5.png)

**Comment by cpiponiot** [comment]
Weird, when I try with *Quercus rubra* in SCBI I don't get the decrease in AGB: 
```
remotes::install_github("forestgeo/allodb")
library(allodb)
dbh = 1:200
agb = get_biomass(dbh, genus = rep("Quercus", 200), species = rep("rubra", 200), coords = c(-78.2, 38.9))
plot(dbh, agb, type="l")
```

![image](https://user-images.githubusercontent.com/20208665/90544046-db56fd80-e186-11ea-9fc3-7e725c408f8e.png)

I haven't tried with other species or sites, but if this happens only when you compute several species together it might be because of bad taxo weight attribution (basically the cause of the wiggles that I thought I had solved)...

**Comment by ValentineHerr** [comment]
Yes indeed, it does seem that I am not getting the issue when I run `get_biomass` on an individual core (or even all cores from that site and species)... but when I have another species in the same subset (or the same species but from a different site), I do get negative biomass increments. So that means that the output of `get_biomass` does change depending on the subset.

Maybe I'll run the function core by core...

**Comment by cpiponiot** [comment]
Thanks for checking that! It then means that the weight function is not working correctly and mixing up weights...
Running it core by core will be a quick fix but we should solve this problem in allodb anyway. Are you sure you have the last version of the package? And could you send me a subset of your dataset for which this problem appears please?

**Comment by ValentineHerr** [comment]
Yes, I am using the latest version.

try this:
```
X <- read.csv("https://raw.githubusercontent.com/EcoClimLab/ForestGEO_dendro/master/data_processed/all_cores_for_Camille_to_check.csv?token=AEWDCIK42K7762BKRGQDMN27IZRYS")


dbh = X$dbh[]
genus = X$genus[]
species = X$species[]
coords = X[, c("Longitude", "Latitude")]
agb = get_biomass(dbh, genus = genus, species = species, coords = coords)
which(sapply(tapply(agb, X$coreID[], diff), function(x) any(x<0)))# gives what cores has a negative agb incremenent, here SCBI.80491

#now doing the same but for that specific core only
idx <- X$coreID %in% "SCBI.80491"
dbh = X$dbh[idx]
genus = X$genus[idx]
species = X$species[idx]
coords = X[idx, c("Longitude", "Latitude")]
agb = get_biomass(dbh, genus = genus, species = species, coords = coords)
which(sapply(tapply(agb, X$coreID[idx], diff), function(x) any(x<0))) # now there is none
any(diff(agb) <0)

```

**Comment by cpiponiot** [comment]
@ValentineHerr could you put the same data online again (or at least the first 15 lines + the problematic tree) please? I wanted to use it again to try and solve this issue and couldn't download it

**Comment by ValentineHerr** [comment]
The data is still there but the token might have changed...
sorry for that.

Try with this URL:
 https://raw.githubusercontent.com/EcoClimLab/ForestGEO_dendro/master/data_processed/all_cores_for_Camille_to_check.csv?token=AEWDCILNU2AK533CZF2ZJ2S7J7F72

**Comment by cpiponiot** [comment]
no worries, thanks!

**Comment by ValentineHerr** [comment]
FYI, I still have non-monotonous cases but also, Picea mariana seems to have too big of an agb for small DBHs (see left side of this plot)  

and e.g 'get_biomass(dbh = 0.46, genus = "Picea", species = "mariana", coords = c(-121.3, 61.3))' gives a very high value for such a tiny tree...


![image](https://user-images.githubusercontent.com/19673377/92947020-7315d780-f425-11ea-9ff9-fddc826fbc72.png)
(note that units in the plot of Mg of C)

**Comment by cpiponiot** [comment]
Monotonicity is no longer an issue with the new allodb version (monotonic allometries are recalibrated)

**Comment by ValentineHerr** [comment]
New version works great and fast. Just to finish here, this is the new version of the plot above:
![image](https://user-images.githubusercontent.com/19673377/103903203-9a29a080-50c9-11eb-996e-dfca3a30d064.png)
(ignore top right, this is new data - and ignore scale, I think? might have been before or after unit conversions)
