### ISSUE TITLE
dependent variables - Total aboveground biomass vs Whole tree / Stem biomass

### ISSUE THREAD

**Issue by cpiponiot** [forestgeo/allodb#108]
Should we group some dependent variables in the `get_biomass` function? I'm thinking for example of equations that have `'Whole tree (above stump)'` or `Stem biomass'` as a dependent variable: can it be used when `var = 'Total aboveground biomass'`? For now, the equations that do not have `'Total aboveground biomass'` in the `dependent_variable` column are not used in the default settings.

**Comment by teixeirak** [comment]
Yes, definitely. The two examples you give seem like instances where they should definitely be grouped (although not sure if `stem biomass` includes branches. @gonzalezeb can provide better guidance than I can.

There will be some where you have to add components (e.g., stem + branches ). Again Erika can give some examples/ provide guidance.

**Comment by gonzalezeb** [comment]
Good point, however for many species, I already added components like stem biomass+branches+foliage+ bark and created a `Total aboveground biomass` equation. Those equations have in the note column "_This equation is not in original pub, we combined plant parts here to obtain AGB_". Notice that I only combined equations when they came from same study.

We could add plants parts programatically in  `get_biomass` and eliminate those combined equations. The issue will come when we have only a stem biomass equation and no other plant component for certain species. See for example, equations from _clark_1986b_wvap_ and some from _jenkins_2004_cdod_ (eq ids= 5ea2c1, 7992d5, c59e03)


For those equations with "Whole tree" I think we can include them now in `var = 'Total aboveground biomass'`

What do you think Camille?

**Comment by teixeirak** [comment]
Oh, I forgot that you did that, @gonzalezeb. That takes care of the second part of my comment above.

**Comment by cpiponiot** [comment]
I think either way works, let's leave it the way it is now. And if `Whole tree` and `Total aboveground biomass` are equivalent I can add `Whole tree` to the default settings. 
@gonzalezeb fyi this issue is the reason why some equations did not appear when they should, e.g. for *Abies amabilis* and *Tsuga spp.*: in the publication from Krumlin et al. 1974 the dependent variable is `Whole tree` so the equations were not being used at all.

**Comment by cpiponiot** [comment]
These are all the dependent variables in the table:
-`Total aboveground biomass`, 
- `Height`, 
- `Whole tree (above stump)`, 
- `Stem biomass (with bark)`, 
- `Stem biomass (without bark)`, 
- `Bark biomass`, 
- `Branches total (live, dead)`, 
- `Foliage total`, 
- `Stem (wood only)`, 
- `Crown biomass (branches, foliage, twigs)`, 
- `Whole tree (above and belowground)`, 
- `Branches (live)`, 
- `Crown (live)`, 
- `Branches (dead)`, 
- `Stem biomass`, 
- `Leaves`  

I added `Whole tree (above stump)` to the default settings (which already had `Total aboveground biomass`): do you think I should add anything else? I think most users will just go with the default settings, so all other equations won't be used in most cases.

**Comment by teixeirak** [comment]
I think a number of those would already be included in the combined equations that Erika made, right @gonzalezeb ?

Perhaps stem biomass (with bark) would be relevant, as leaves would be a fairly small portion of the weight. @gonzalezeb can probably give a better answer on that.

**Comment by teixeirak** [comment]
Ultimately, it would be good for the user to be able to select a dependent variable other than AGB, but at this point we don't have enough equations for anything but AGB.

**Comment by cpiponiot** [comment]
It is possible, the `var` argument can be changed to anything else (but by default it is `var = c(Total aboveground biomass, Whole tree (above stump))` , which I think most users won't change). We can print a warning message when other dependent variables are chosen and the total sample size/number of equations is small.

**Comment by gonzalezeb** [comment]
I agree with Camille, a warning message will do the part. 
Notice that I updated the list of dependent_ variable in equation table, now they are:

_Bark
Branches (dead)
Branches (live)
Branches (live, dead)
Crown (branches, foliage, twigs)
Foliage
Height
Stem biomass (with bark)
Stem biomass (without bark)
Total aboveground biomass
Whole tree (above and belowground)
Whole tree (above stump)_



To answer Krista's questions:
> I think a number of those would already be included in the combined equations that Erika made, right @gonzalezeb ?

Yes, but they remain in the eq  table,in case anyone just want to calculate foliage biomass, for example..
> 
> Perhaps stem biomass (with bark) would be relevant, as leaves would be a fairly small portion of the weight. @gonzalezeb can probably give a better answer on that.

Yes, but if we include _stem biomass (with bark)_ in `var = c(` then few of those equations would be used twice when weighting equations (?) (i.e., for those species where I combined various components).  Let me think about it....

**Comment by teixeirak** [comment]
Thanks, Erika. This all sounds good.
