### ISSUE TITLE
(How) do we handle anomalous taxonomic groups that require taxa-specific allometries

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#110]
@gonzalezeb , @cpiponiot ,

Here is some text from Erika's current manuscript draft:

`Some taxonomic groups are better described by taxa-specific allometries. Some plant taxa do not conform to generalized allometries and can only be reasonably described by taxa-specific allometries to estimate biomass (Goodman et al. 2013). For example, in an Australia-wide analysis including 53 species, 8% of species were not well described by generalized allometries (Paul et al. 2016). Across ForestGEO sites, few taxa are known to not conform to generalized allometries and therefore were described by species-specific functions, including palms (Goodman et al. 2013; Návar 2009) and tree ferns (genera Cyathea: Tiepolo, Calmon, and Feretti 2002; and Cibotium: Asner et al. 2011). `

At present, we don't have a mechanism for dealing with such cases. So far, I think all the known cases are tropical, so we may not need to deal with it (now). But it's a potential challenge to our system/ something to think about.

**Comment by cpiponiot** [comment]
Yes, for now the only way to do it is to calculate AGB for those taxa with a separate equation table (which can be done by subsetting the current equation table, and/or adding new equations, and using it in the get_biomass function instead of the default equation table). We can maybe think of a better way to deal with this

**Comment by teixeirak** [comment]
I don't think it needs to be done for Erika's pub, but something to keep in mind.
