### ISSUE TITLE
Infinite agb output

### ISSUE THREAD

**Issue by ValentineHerr** [forestgeo/allodb#113]
This may have been happening for a while, but just notice it now. 
Some agb calculated with get_biomass are `Inf`. These are the sites and species where it is happening (for me) along with the dbh range (1 is min, 2 is max) at which it happens:

![image](https://user-images.githubusercontent.com/19673377/90060254-69784300-dcb2-11ea-8a52-53fc034c956c.png)

**Comment by cpiponiot** [comment]
@ValentineHerr this should be solved now, I checked with some species from SCBI but if you get the same problem again please let me know

**Comment by ValentineHerr** [comment]
that worked for me!
