### ISSUE TITLE
giving more flexibility in the weighting scheme

### ISSUE THREAD

**Issue by cpiponiot** [forestgeo/allodb#114]
For now there is no arguments of the get_biomass function that allow the user to change the parameters of the weighting scheme (mentioned in the allodb manuscript: "The choices of weighting functions and parameter values are somehow arbitrary, selected based on our current understanding of the principles of allometric equations and experimentation with various options, **and may be adjusted based on user discretion**")

Should I add these arguments in the get_biomass function, with the same default values as the ones already given now?

**Comment by gonzalezeb** [comment]
I think that would be good, it is kind of facilitating steps to the user on how to change parameters.

**Comment by teixeirak** [comment]
Yes, I think that's good,  assuming its easy to implement.
