### ISSUE TITLE
new approach to allodb

### ISSUE THREAD

**Issue by cpiponiot** [forestgeo/allodb#118]
Here is an idea that I think should solve a lot of the problems we've been having with `allodb`, in particular with equations that give weird results outside of their DBH range and monotonicity issues. Plus we could provide an estimation of uncertainty on predictions. The more I think about it the more convinced I am that it's the way to go. But it would require some time to implement (which I'm not sure I'll have), and it would mean some serious rewriting of the methods in the paper, so we should probably discuss it before doing anything. 

The idea is to recalibrate new allometric equations per species x site every time we run the `get_biomass` function (somehow similar to Chojnacky et al. 2014). It should be faster than the way we do it now, especially for large datasets, because we don't need to have a weight associated with each observation. 

So we would have a `species_allometry` function that recalibrates allometries for each species x site combination in the provided dataset (e.g. a forest census) by (1) resampling from the original equations,  and (2) fitting a new allometry log(AGB) ~ N(a + log(DBH) * b, sigma^2). The outputs of the function are a set of parameters (a, b, sigma) for each species x site combination, that will then be used to estimate the AGB of each observation in the `get_biomass` function. 

- the number of resampled values per original equation should be proportional to the equation's weight (based on sample size, climatic similarity to the site, and taxonomic similarity to the species), 
- the DBHs of resampled values are taken in a uniform (or other) distribution within the DBH range of each original equation,
- the AGB of resampled values can be either the mean prediction from the original equation or a value taken in their distribution if we have enough equations with information such as R^2 or standard deviation. For equations that don't have that information, we can think of a generic standard deviation.

**Comment by teixeirak** [comment]
This sounds like a good approach, and a great thing to do if you have time. If not, we can save it as a future improvement. This also may depend somewhat on the reviews that we get back, and on @gonzalezeb 's feelings on this.

**Comment by gonzalezeb** [comment]
I think this sounds great Camille, a little bit of extra work on our side but very positive if we can estimate uncertainty of predictions and the process would be faster specially for large datasets. Let's wait for reviews and then take some steps.
