### ISSUE TITLE
Make examples run faster

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#138]
This is not urgent but it's nice to have. Examples should run in 5 seconds or less. The exact time is hard to predict because it depends on the computer running it -- which is sometimes a computer we don't control (e.g. CRAN servers). Yet this note signs we should likely make the examples of these functions faster:

```r
> checking examples ... NOTE
  Examples with CPU (user + system) or elapsed time > 5s
                user system elapsed
  get_biomass 11.205  0.004  11.212
  est_params   5.367  0.039   5.406
```

**Comment by cpiponiot** [comment]
I reduced the number of species in the examples, which makes them run faster (around 0.3 sec for each example on my computer)

**Comment by gonzalezeb** [comment]
This is great Camille, thank you!. Closing issue now.
