### ISSUE TITLE
Checks not passing

### ISSUE THREAD

**Issue by gonzalezeb** [forestgeo/allodb#146]
R CMD checks [rcmdcheck::rcmdcheck()] nor devtools::test() are passing mostly because an issue on the get_biomass function, can @maurolepore or @cpiponiot  see -or can solve- the problem? Sorry, I just don't have the technical expertise to solve these issues quickly enough..

```r
> get_biomass(
+   dbh = 50, 
+   genus = "liriodendron", 
+   species = "tulipifera", 
+   coords = c(-78.2, 38.9)
+ )
Error in `colnames<-`(`*tmp*`, value = c("long", "lat")) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

**Comment by cpiponiot** [comment]
Ok, I think I found the problem, it's that the order of the arguments in several functions has changed. I will make the necessary changes in the codes
