### ISSUE TITLE
Define a process to screen allometries

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#16]
We'll want to set bonds on what should be considered a reasonable biomass estimate and flag any allometries that fall outside of this range.

The first step is to define how those bounds should be determined.

**Comment by teixeirak** [comment]
Issue #73 will allow visual inspection, which is sufficient for minimum viable product. Formal code tests will be a lower-priority enhancement.

**Comment by gonzalezeb** [comment]
This issue now relates and it may solved by #96, so I am closing it.

We will weight allometric models (basically rank) based on available information.
