### ISSUE TITLE
README not showing graphs or tibble

### ISSUE THREAD

**Issue by gonzalezeb** [forestgeo/allodb#161]
It would be nice to show some graphs in the main documentation of the [package website](https://forestgeo.github.io/allodb/index.html), but there is an issue: when I knit the README.Rmd file, the coded 2 graphs and tibble don't show in the preview (nor in the website).

However, when I run the following chunk (for example), the graph is shown in the Text editor window with no problems..

Hi @maurolepore, maybe you can give me a hand here...

![image](https://user-images.githubusercontent.com/26872628/133541765-9cd74cb9-aa90-4920-aa40-46ae5d066bcf.png)

**Comment by maurolepore** [comment]
In the chunk options I see `eval = FALSE` (do you know why?). If you want that chunk to be evaluated, then remove `eval = FALSE` or change it to `eval = TRUE`.

**Comment by gonzalezeb** [comment]
Done, thanks!
