### ISSUE TITLE
Deal with disconnects between equations that switch when trees cross a size threshhold 

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#17]
The database will allow application of different equations to trees of different size (e.g., switch from a highly specific allometry for small sizes to a more generic one at sizes above that sampled for the specific one). This is desirable. However, when a tree crosses a size threshold, estimates of woody growth and ANPP will be seriously flawed. To address this, we need to incorporate code that forces the application of only one allometric equation-- even outside its range--to trees that grow over such a threshhold.

**Comment by teixeirak** [comment]
In cases where we transition from one equation to another as tree size increases, we should select the equation based where the lines cross rather than the min/max DBH associated to each allometry. For instance, for Liriodendron, small trees are described by a function that accelerates rapidly with DBH, and larger trees by a more gradual function. Based on the min/max diameters for each equation, trees would grow and then shrink by quite a bit when you transition to the new equation. Rather than allow this, we should switch to the large tree equation when the small-tree equation gets above what it would predict. (Sorry, I didn't save the plot showing this example, but it would be easy to reconstruct.)

**Comment by gonzalezeb** [comment]
Closing issue. This was solve with the weighting system.
