### ISSUE TITLE
Include warning/ error messages when unreliable allometries are applied

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#18]
Jim Lutz recommends that the R code should generate warning messages when unreliable allometries are applied.

There are several issues that need to be decided:

1. What are the criteria that should generate a warning / error message? Here's the start of a list:
- [ ] attempt to apply allometric equation outside of the DBH range for which it was developed
- [ ] attempt to apply a generic equation to a species for which its a terrible fit (see item 2)
- [ ] application of an allometry that is of poor quality (e.g., low number of individuals sampled) but still the best available. For this, we need to decide criteria.

2. Should the code allow bad allometries to be applied? A couple examples:
- if the user selects the generic equation option, which is very bad for bristlecone pine, should there be a warning message : “you can use this general equation, but its going to be really bad for bristlecone pine”, or should the expert-selected allometry automatically be applied?  
- if an allometry is assigned outside the DBH range for which it was developed, should this generate a warning (i.e., message, code still runs) or an error (i.e., code won't run unless fixed)?

3. How is this implemented in the database and code?
- I think that one way to implement this in the database is to add a warning_notes field to both allodb_equations.csv (warnings about the allometric equation itself) and allodb_site_species.csv (warnings about application of an allometric equation to a certain tree). These can be used to manually add warnings that should be displayed when the allometry is applied.

**Comment by gonzalezeb** [comment]
@cpiponiot Let's try to discuss some aspects of this issue today 5/12.
