### ISSUE TITLE
Handle height allometries

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#19]
Some sites have local height allometries, which can be used to improve estimates.

We need to plan the structure for incorporating these in the database.

This is something that @gonzalezeb, @maurolepore, and @teixeirak should discuss in person.

**Comment by maurolepore** [comment]
Originally from https://github.com/forestgeo/allodb/issues/67#issuecomment-472105558

> ... I see two issues in particular that may present problems:

> 1. There's a potential incompatibility with BIOMASS when it comes to the approach is in the handling of height allometries. Some of our sites have height allometries, which are to be included in our equations table. However, the BIOMASS package uses raw height data to calculate an allometry. I do not know that we can pass it an equation. Alternatively, we could easily put the equation in our table and calculate values for those species within allodb. @maurolepore, this will be something for you to look into.

Sorry, I can't understand enough to write any comment that makes sense. I just acknowledge I've ready this and I need carification. An example would help. In any case, you seem to have an alternative solution, so great!

**Comment by teixeirak** [comment]
This is not necessary for the minimum viable product, but should be dealt with before publication of the paper.

**Comment by teixeirak** [comment]
@gonzalezeb, [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4377263/) is the one I mentioned with height allometries.

**Comment by maurolepore** [comment]
>  (Krista) revise code to deal with instances where a height allometry is available (@maurolepore)

> (Ervan) Chave et al. 2014 are also providing a general equation to estimate height.

A branch of fgeo.biomass now wraps the BIOMASS package and provides a way to estimate height based on a `region` or on `latitude` and `longitude`. It does this internally (https://github.com/forestgeo/allodb/issues/54#issuecomment-483344238). I believe this is appropriate for tropical species only. 

Relates to https://github.com/forestgeo/allodb/issues/54#issuecomment-483723740

**Comment by gonzalezeb** [comment]
Now we only need:
- decide if we need a height allometry ID field in site_species table in allodb
- include a line in the code in fgeo.biomass to use height equations from allodb when height is needed to calculate biomass in a non tropical site.

**Comment by teixeirak** [comment]
> Now we only need:
> 
>     * decide if we need a height allometry ID field in site_species table in allodb

Yes.

**Comment by gonzalezeb** [comment]
Closing. Height allometries are now handle by the get_biomass function
