### ISSUE TITLE
Assess wood density data situation, make plan

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#20]
- [x] touch base with Nate S about the origins of CTFS wood density data file
- [x] @ervanSTRI , could you please tell us about the wood density values you're using?
- [x] touch base with Amy Zanne/ Jerome Chave to learn status of wood density database (we hear that Jerome has a postdoc working on this and that Amy is also involved)
- [x] write code to extract relevant data from wood density database
    (consider [this vignette of the __BIOMASS__ package](https://cran.r-project.org/web/packages/BIOMASS/vignettes/VignetteBiomass.html) and code by Ervan).
- [ ] try to track down other sources that contributed to database (otherwise they probably have to be dropped). A comparison of what's in the Zanne/ Chave global database versus the CTFS wood density file may help to identify site-specific data that have made it into our database.
- [ ] add any available CTFS - specific data (with documentation)

**Comment by teixeirak** [comment]
Here is the website for the global wood density database: http://wooddensity.univ-tlse3.fr.

**Comment by gonzalezeb** [comment]
Closing issue as we don't use wood density in allodb process.
