### ISSUE TITLE
Document all data in data/

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#33]
Create R/data.R and create the roxygen skeleton to document all datasets in data/. Then ask Erika to fill the gaps in the documentation, reveal the missing datasets, and the missmatches between the data and the data_metadata -- which BTW may need to be specified programatically so it doesn't come out of sync (via some function that would compare the names of the columns in each data set with the values of "Field" in its corresponding metadata-dataset).

**Comment by gonzalezeb** [comment]
Just tried to improve documentation but got stuck with my lack of skills (ie. how to built a table that will go under 'Format' when calling ?equations...)..We can work on this later.

**Comment by maurolepore** [comment]
There is the roxygen tag @format. IT would look like this:
```R
#' @format 
#' stuff
```

But I haven't used @format a lot so I'm unsure what you can and can't do in it. Can I see the table you want to add?

**Comment by gonzalezeb** [comment]
I want `equation_metadata` to look like the table in ?datasets::airquality when using the help file for ?equation

I tried something in commit 1cafffb, but nothing happened

**Comment by maurolepore** [comment]
```
#' Tables of allometric equations and associated metadata for ForestGEO sites.
#'
#' A dataset of best available allometry equations to calculate AGB per species
#' per ForestGEO site:
#' * `equations`: Table of allometric equations.
#' * `equations_metadata`: Table of metadata of `equations`.
#'
#' @details
#' A data frame with 154 observations on 6 variables.
#' @details
#' ```
#' [,1]	Ozone	 numeric	 Ozone (ppb)
#' [,2]	Solar.R	 numeric	 Solar R (lang)
#' [,3]	Wind	 numeric	 Wind (mph)
#' [,4]	Temp	 numeric	 Temperature (degrees F)
#' [,5]	Month	 numeric	 Month (1--12)
#' [,6]	Day	 numeric	 Day of month (1--31)
#' ```
"equations"

#' @rdname equations
"equations_metadata"
```
![image](https://user-images.githubusercontent.com/5856545/47678929-52c63200-db99-11e8-918d-9727cd000982.png)

**Comment by maurolepore** [comment]
I'll push tihis one.

```
#' Tables of allometric equations and associated metadata for ForestGEO sites.
#'
#' A dataset of best available allometry equations to calculate AGB per species
#' per ForestGEO site:
#' * `equations`: Table of allometric equations.
#' * `equations_metadata`: Table of metadata of `equations`.
#'
#' @format
#' A data frame with 154 observations on 6 variables.
#' ```
#' [,1]	Ozone	 numeric	 Ozone (ppb)
#' [,2]	Solar.R	 numeric	 Solar R (lang)
#' [,3]	Wind	 numeric	 Wind (mph)
#' [,4]	Temp	 numeric	 Temperature (degrees F)
#' [,5]	Month	 numeric	 Month (1--12)
#' [,6]	Day	 numeric	 Day of month (1--31)
#' ```
"equations"
```

![image](https://user-images.githubusercontent.com/5856545/47679070-b18bab80-db99-11e8-8f67-e7bb28a980ca.png)

**Comment by gonzalezeb** [comment]
Closing (finally!) because all functions and datasets have been documented
