### ISSUE TITLE
Ensure all equations contain valid R code

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#38]
I plan to write a test to automatically check that each equation can be evaluated -- i.e. that it contains valid R code. Once that is done, we'll be able to press `Control + Shift + T` to run this (and all other) test, and we'll get an informative error message if some equation isn't valid R code.

**Comment by maurolepore** [comment]
@gonzalezeb, [here ](https://bookdown.org/fgeocomm/38_valid_eqn/) I point to some equations that currently contain invalid code and I suggest the solutions. Let me know if you have questions or need help.

**Comment by gonzalezeb** [comment]
This is great Mauro.  Two fixes can be applied now and I will work on the other two: 

fix_problem("attempt", "([0-9])(\\(log10)", "\\1 * \\2")  
fix_problem("unexpected ')'", "\\)$", "")

A questions for you: I would like the changes to be applied to our master table (data-raw/allodb-master) but as the code is written now changes would be applied to data/equations. How do I work around it?

**Comment by maurolepore** [comment]
You are right, the equations come from the equation table, and the changes are not applied back to any table. 

```R
eqn <- equations$equation_allometry`.
```

You could do something like this:

```R
# Inputs a vector and outputs a dataframe
fixed_dataframe <- fix_problem(master$equations, ...)

master$equations <- fixed_dataframe$equations
```

This kind of "find and replace" you could also do in excel. But go for it if you want to do it in R. I think it's the best way to learn.

**Comment by gonzalezeb** [comment]
I reviewed and fixed the equations (the easiest way!). thanks Mauro.  For dba or what I call, the srub problem please see issue #41

**Comment by maurolepore** [comment]
Great work @gonzalezeb; thanks!

Now all except one error relates to 'dba' (#41). The exception relates to 'BA'. What should we do about that? ([details](https://bookdown.org/fgeocomm/38_valid_eqn/)).

![image](https://user-images.githubusercontent.com/5856545/40512378-a555a3ca-5f70-11e8-9429-cf45b16ad5a9.png)

**Comment by maurolepore** [comment]
Relates to #54 .
