### ISSUE TITLE
Shrubs biomass calculation in temperate forests

### ISSUE THREAD

**Issue by gonzalezeb** [forestgeo/allodb#41]
This issue is in relation to issue #38, about the use of dba (diameter at stem base) in shrub allometries. 
I have summarized what I think is the correct way to present these calculations. I will need Mauro’s help to convert this into a function that depends only on DBH. 

**Problem** (this paragraph can be included in the description of the function):

Most available equations to calculate shrub biomass in temperate regions (Smith et al 1983, Lutz et al, 2014, Halpern and Millet, 1996) use diameter at the base of the stem (15 cm above ground or close to ground) as independent variable. Given that at CTFS-ForestGEO plots the standardized diameter measurement for woody stems is at breast height (DBH, 1.37 m), we WROTE a function to use stem DBH as input to calculate biomass for some shrub species (see site.species table). We suggest the following:

**Potential solution** (where I need help)..

Step 1=Calculate the basal area contribution of each stem within a tree
BA <- (pi/4) * dataset$dbh^2 
Step 2= Sum of basal area of each stem to get basal area of per tree
tree.sum.BA.un <- tapply(BA, dataset$tag, sum, na.rm = T) 
Step 3= Calculate the contribution of each stem to sum of basal area of a tree
BA.contribution <- BA / tree.sum.BA 

a)	If an allometry equation use DBA (diameter at base) as independent variable then:
Step 4= calculate the diameter at the base of shrub, assuming area preserving
Step 5= calculate AGB using the basal diameter equation (a*(DBA^b) or exp(a+b*ln(DBA))
Step 6= Redistribute the biomass of the main stem to other stems, using the basal area contribution

b) If DBH is the independent variable in the equation (assuming that only the diameter of the main stem was measured in a shrub), then:
Step 4= identify the main stem (stem with the largest DBH).
Step 5= calculate AGB using DBH of main stem
Step 6= redistribute the biomass to other stems within the tree, using the basal contribution of each stem.

**Comment by maurolepore** [comment]
This is mainly to organize my thoughts. I plan to edit this comment as I clarify my thinking. For now I need no input. I'll ask specific questions later.

The steps described above concern the entire process for calculating biomass. For now, however, I would like to focus on the specific process to translate DBH (from users data) to DBA (required in some equations). With that translation we can then calculate the biomass of each individual stem (each row in a dataset with a DBH value), and then users can summarize the data however they want, e.g. totals by tag, species, quadrat.

Notice that once we translate DBH to DBA, the two pathways merge. That is, we no longer have a pathway (a) and a pathway (b), but a table with equations dependent on DBH or DBA that we can evaluate using DBH values from the user.

Some more general thoughts that I’ll clarify as I reveal the differences between the processes to calculate biomass of shrubs versus anything 

* How are shrubs identified in the equations table?

* Is it appropriate to mix shrubs with other woods in the same table? Or is it more sensible to pull shrubs out into a separate table? (This we could do programatically so the master table remains the single interface to enter data.)

* Do we want users to have two functions, one for biomass of shrubs and another one for everything else? Or do we want to hide the different processes inside a single 

    * Pro of separate functions: It's more transparent because the user has to explicitly calculate biomass for shrubs and other woods separately.

    * Con of separate functions: If it is very common that users will need to run the two functions every time, then the extra action, although small, becomes inconvenient.

**Comment by maurolepore** [comment]
I may be very wrong, so please correct me.

If BD is equivalent to DBA, then Valentine's code shows that DBH and DBA are equivalent when the number of stems in a shrub is one. That means that to calculate the biomass of each individual stem in a shrub we can use directly DBH.

However, I'm confused when it comes to calculating the total biomass in a stem. It seems intuitive that the combined biomass of all stems of a shrub should be the sum of the biomass of the individual stems. Yet the equations I get show that the result is instead the square root of the sum of each DBH to the power of two (`sqrt( dbh1^2 + dbh2^2 + ... )`).

![image](https://user-images.githubusercontent.com/5856545/40555601-a38573de-6017-11e8-823c-379e4be62b61.png)

----

From Valentine's code

```R
## calculate basal area contribution of each stem within a tree
BA <- (pi / 4) * x.shrub.BD$dbh^2 # basal area (at 1.3 m) in mm
tree.sum.BA.un <- tapply(BA, x.shrub.BD$tag, sum, na.rm = T) # sum of basal areas per tree

# ... more code here

## calulate diameter at base of shrub, assuming area preserving
tree.BD <- data.frame(tag = names(tree.sum.BA.un), BD = sqrt(tree.sum.BA.un / pi) * 2)
```
`tree.sum.BA.un` is the sum of basal areas per tree. Next I explore the cases when a shrub has a single stem, then when it has multiple stems.

## Case when a shrub has one stem

When a shrub has one stem, the sum of basal area equal basal area:

```R
tree.sum.BA.un = BA = (pi / 4) * dbh^2
```
Inserting BA into the formula of BD we can simplify terms until we end up with DBH. If follows:

```R
BD = sqrt(tree.sum.BA.un              / pi)             * 2 = 
     sqrt(BA                          / pi)             * 2 =
     sqrt((pi / 4)            * dbh^2 / pi)             * 2 = 
     sqrt( pi / 4             * dbh^2 / pi)             * 2 = 
     sqrt( 1  / 4             * dbh^2     )             * 2 = 
     sqrt( 1  / 2^(1/2)       * dbh^2     )             * 2 = 
     sqrt(1)  / sqrt(2^(1/2)) * sqrt(dbh^2)             * 2 = 
     1        / 2             * dbh                     * 2 = 
                                dbh/2                   * 2 = 
                                dbh                         = BD
```

## Case when a shrub has multiple stems

```R
BD = sqrt(tree.sum.BA.un               / pi)             * 2 = 
     sqrt(BA1 + BA2                    / pi)             * 2 =
     sqrt(  pi / 4 * (dbh1^2 + dbh2^2) / pi)             * 2 = 
     sqrt(4) *   sqrt(dbh1^2 + dbh2^2)                   * 2 = 
     2       *   sqrt(dbh1^2 + dbh2^2)                   * 2 = 
                 sqrt(dbh1^2 + dbh2^2)                       = 
                 sqrt(dbh1^2 + dbh2^2)                       = 
```

**Comment by maurolepore** [comment]
@gonzalezeb, whenever you can, I'd love to have your thoughts (and maybe Valentine's) about my idea that DBH and DBA may be equivalent (comment just above this one).

**Comment by gonzalezeb** [comment]
Mauro, we think your approach is correct. DBH is equivalent to DBA when the shrub has only one stem. But when it has multiple stem, we  just need to make sure to redistribute the biomass of main stem to other stems. Valentine has something to add @ValentineHerr

**Comment by gonzalezeb** [comment]
I think I will include @ValentineHerr if we have more questions..

**Comment by ValentineHerr** [comment]
Hi @maurolepore ,
I will try to clarify the thinking process for the shrub allometric equation here:

A - If the **DBH** is needed (equations probably developed for shrubs that have a "tree" shape, with some branches along the stem), we need to apply the equation on the **main stem** of the shrub because we think that studies outside of ForestGEO do not measure every single stem at 1.3m but instead find the main obvious stem and measure that one only. From that one stem they get the whole AGB. If we were applying the equation on every single stem of the shrub we would overestimate the AGB because it would be assuming that each stem is actually its own shrub. 
Once the equation is applied on the main stem, we get one AGB that needs to be redistributed to all stems, proportionally.

B. If the **Basal Diameter** is needed (equations probably developed for shrubs that have all their stems coming out of the stump), we need to estimate that basal diameter. Krista's idea was to assume "area preserving" which means that the sum of the area of all stems at 1.3m is equal to the area at the stump. From that basal area that we just calculated, we get the basal diameter (You found our that we can use the sqrt( dbh1^2 + dbh2^2 + ... ) instead of doing the whole area preserving calculation. Good). 
Once the equation is applied on the one basal diameter, we get one AGB that needs to be redistributed to all stems, proportionally.

Is that clarification of any help ?

**Comment by maurolepore** [comment]
Adding to https://github.com/forestgeo/allodb/issues/41#issuecomment-395201329, this flowchart highlights diffences between stem and tree tables for tree and shrub life forms. I'll develop my thougths and code a bit more then may ask a few questions.

![IMG-4391](https://user-images.githubusercontent.com/5856545/55348289-e40d3d80-5484-11e9-9d69-90ed766e5169.JPG)

**Comment by maurolepore** [comment]
What criteria should I use to pick the equations that follow the path that @ValentineHerr described above for shrubs?

The division is less clear than I had expected. Below you can see equations which independent variable is `dbh` for "Shrub", for "Tree", and for "Tree or Shrub", and for "Shrub, small tree".


``` r
library(tidyverse)

allodb::master_tidy() %>% 
  select(life_form, equation_form, independent_variable) %>% 
  unique()
#> Joining `equations` and `sitespecies` by 'equation_id'; then `sites_info` by 'site'.
#> # A tibble: 31 x 3
#>    life_form         equation_form           independent_variable
#>    <chr>             <chr>                   <chr>               
#>  1 Tree              10^(a+b*(log10(dbh^c))) DBH                 
#>  2 Tree              exp(a+b*log(dbh))       DBH                 
#>  3 Tree              10^(a+b*(log10(dbh)))   DBH                 
#>  4 Shrub             exp(a+b*log(dbh))       DBH                 
#>  5 Shrub, small tree exp(a+b*log(dbh))       DBH                 
#>  6 Tree or Shrub     exp(a+b*log(dbh))       DBH                 
#>  7 Tree              a+(b*dbh)+c*(dbh^d)     DBH                 
#>  8 Shrub             a*(dba^b)               DBA                 
#>  9 Tree              a*(dbh^b)               DBH                 
#> 10 Shrub             a*(dbh^b)               DBH                 
#> # ... with 21 more rows
```

Created on 2019-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by gonzalezeb** [comment]
I think your suggestion is good ("anything containing "shrub" is a shrub).
I can work more to refine when species life_form=Tree or Shrub. That's something I have to use when working with generic equations.

**Comment by maurolepore** [comment]
We now correclty handly shrub biomass for equaitons which independent variable is `dbh`. This example shows a small table with shrubs exclusively:
``` r
library(tidyverse)
library(fgeo.biomass)

shrubs <- fgeo.biomass::scbi_stem_shrub_tiny

equations <- shrubs %>%
  add_species(scbi_species, "scbi") %>%
  allo_find(dbh_unit = "mm")
#> Adding `site`.
#> Overwriting `sp`; it now stores Latin species names.
#> Adding `rowid`.
#> * Matching equations by site and species.
#> * Refining equations according to dbh.
#> * Using generic equations where expert equations can't be found.
#> Warning: Can't find equations for 26 rows (inserting `NA`).

biomass <- equations %>% 
  allo_evaluate(dbh_unit = "mm")
#> Shrub `biomass` given for main stems only but applies to the whole shrub.
#> Guessing `dbh` in [mm]
#> You may provide the `dbh` unit manually via the argument `dbh_unit`.
#> Converting `dbh` based on `dbh_unit`.
#> `biomass` values are given in [kg].
#> Warning: Can't convert all units (inserting 26 missing values):
#> the 'to' argument is not an acceptable unit.
#> Warning: Can't convert all units (inserting 26 missing values):
#> the 'from' argument is not an acceptable unit.

# Biomass given only for main stem but representes whole shrub biomass
with_biomass <- left_join(equations, biomass) %>% 
  select(1:6, dbh, biomass)
#> Joining, by = "rowid"
with_biomass
#> # A tibble: 34 x 8
#>    rowid treeID stemID   tag StemTag sp                dbh biomass
#>    <int>  <dbl>  <dbl> <dbl>   <dbl> <chr>           <dbl>   <dbl>
#>  1     1   1111   1111 10133       1 lindera benzoin  50.9    5.56
#>  2     2   1111  32221 10133       2 lindera benzoin  18.5   NA   
#>  3     3   1111  36962 10133       3 lindera benzoin  17.2   NA   
#>  4     4   1111  38540 10133       4 lindera benzoin  17.2   NA   
#>  5     5   1111  39225 10133       5 lindera benzoin  17.1   NA   
#>  6     6   1111  39581 10133       6 lindera benzoin  15.9   NA   
#>  7     7   2333   2333 20035       1 lindera benzoin  56.9    7.27
#>  8     8   2333  32434 20035      10 lindera benzoin  12.1   NA   
#>  9     9   2333  37071 20035      11 lindera benzoin  15.9   NA   
#> 10    10   2333  38598 20035      12 lindera benzoin  11.5   NA   
#> # ... with 24 more rows

# More clearly showing whole-shrub biomass
left_join(equations, biomass) %>% 
  select(1:6, dbh, biomass) %>% 
  group_by(treeID) %>% 
  summarise(whole_shrub_biomass = sum(biomass, na.rm = TRUE))
#> Joining, by = "rowid"
#> # A tibble: 5 x 2
#>   treeID whole_shrub_biomass
#>    <dbl>               <dbl>
#> 1   1111                5.56
#> 2   2333                7.27
#> 3   5476                9.05
#> 4  22479                3.34
#> 5  28182                5.85
```

Created on 2019-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
This example includes both shrubs and trees:


``` r
library(tidyverse)
library(fgeo.biomass)

shrubs <- fgeo.biomass::scbi_stem_shrub_tiny
trees <- fgeo.biomass::scbi_stem_tree_tiny

data <- bind_rows(shrubs, trees)

equations <- data %>%
  add_species(scbi_species, "scbi") %>%
  allo_find(dbh_unit = "mm")
#> Adding `site`.
#> Overwriting `sp`; it now stores Latin species names.
#> Adding `rowid`.
#> * Matching equations by site and species.
#> * Refining equations according to dbh.
#> * Using generic equations where expert equations can't be found.
#> Warning: Can't find equations for 29 rows (inserting `NA`).

biomass <- equations %>% 
  allo_evaluate(dbh_unit = "mm")
#> Shrub `biomass` given for main stems only but applies to the whole shrub.
#> Guessing `dbh` in [mm]
#> You may provide the `dbh` unit manually via the argument `dbh_unit`.
#> Converting `dbh` based on `dbh_unit`.
#> `biomass` values are given in [kg].
#> Warning: Can't convert all units (inserting 29 missing values):
#> the 'to' argument is not an acceptable unit.
#> Warning: Can't convert all units (inserting 29 missing values):
#> the 'from' argument is not an acceptable unit.

# Biomass given only for main stem but representes whole shrub biomass
with_biomass <- left_join(equations, biomass) %>% 
  select(1:6, dbh, biomass)
#> Joining, by = "rowid"
with_biomass
#> # A tibble: 46 x 8
#>    rowid treeID stemID   tag StemTag sp                dbh biomass
#>    <int>  <dbl>  <dbl> <dbl>   <dbl> <chr>           <dbl>   <dbl>
#>  1     1   1111   1111 10133       1 lindera benzoin  50.9    5.56
#>  2     2   1111  32221 10133       2 lindera benzoin  18.5   NA   
#>  3     3   1111  36962 10133       3 lindera benzoin  17.2   NA   
#>  4     4   1111  38540 10133       4 lindera benzoin  17.2   NA   
#>  5     5   1111  39225 10133       5 lindera benzoin  17.1   NA   
#>  6     6   1111  39581 10133       6 lindera benzoin  15.9   NA   
#>  7     7   2333   2333 20035       1 lindera benzoin  56.9    7.27
#>  8     8   2333  32434 20035      10 lindera benzoin  12.1   NA   
#>  9     9   2333  37071 20035      11 lindera benzoin  15.9   NA   
#> 10    10   2333  38598 20035      12 lindera benzoin  11.5   NA   
#> # ... with 36 more rows

# More clearly showing whole-shrub biomass
left_join(equations, biomass) %>% 
  select(1:6, dbh, biomass) %>% 
  group_by(treeID, sp) %>% 
  summarise(whole_shrub_biomass = sum(biomass, na.rm = TRUE))
#> Joining, by = "rowid"
#> # A tibble: 10 x 3
#> # Groups:   treeID [10]
#>    treeID sp                   whole_shrub_biomass
#>     <dbl> <chr>                              <dbl>
#>  1    509 fraxinus americana                497.  
#>  2   1111 lindera benzoin                     5.56
#>  3   2333 lindera benzoin                     7.27
#>  4   5476 lindera benzoin                     9.05
#>  5  12427 carpinus caroliniana               44.6 
#>  6  13505 cercis canadensis                  63.3 
#>  7  22479 lindera benzoin                     3.34
#>  8  25910 juglans nigra                     564.  
#>  9  28182 lindera benzoin                     5.85
#> 10  28551 carya glabra                      430.
```

Created on 2019-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
Here I confirm what I commented at https://github.com/forestgeo/allodb/issues/41#issuecomment-392113712

``` r
diameter_at_base <- function(x) {
  sqrt(sum(x^2, na.rm = TRUE))
}

# Same as 
basal_diameter <- function(dbh) {
  sqrt(sum(basal_area(dbh), na.rm = TRUE) / pi) * 2
}
basal_area <- function(dbh) {
  pi / 4 * dbh^2
}

identical(basal_diameter(10), diameter_at_base(10))
#> [1] TRUE

random_dbh <- runif(10) * 100
random_dbh
#>  [1]  7.409593 64.421704 25.298599 32.595740 78.228289 50.095644 29.966804
#>  [8] 45.656978 15.480379 55.405035
identical(basal_diameter(random_dbh), diameter_at_base(random_dbh))
#> [1] TRUE
```

Created on 2019-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
@gonzalezeb,

For shrub equations which independent variable is `dba` , 

Which diameter does `dbh_min_cm` refer to (in allodb)?
a. The dbh of each individual stem.
b. The dba (diameter at base), calculated from the dbh of all stems together.
c. Other.

``` r
library(tidyverse)

allodb::master_tidy() %>%
  filter(str_detect(equation_form, "dba")) %>% 
  select(equation_form, matches("min|max")) %>% 
  unique()
#> Joining `equations` and `sitespecies` by 'equation_id'; then `sites_info` by 'site'.
#> # A tibble: 18 x 3
#>    equation_form     dbh_min_cm dbh_max_cm
#>    <chr>                  <dbl>      <dbl>
#>  1 a*(dba^b)               0.18       4.31
#>  2 a*(dba^b)               0.12       0.69
#>  3 a*(dba^b)               0.2        1.2 
#>  4 a*(dba^b)               0.3        0.9 
#>  5 a*(dba^b)               0.28       1.59
#>  6 exp(a+b*log(dba))       0.5        2.1 
#>  7 exp(a+b*log(dba))       0.6        2.5 
#>  8 exp(a+b*log(dba))       0.4        1.4 
#>  9 exp(a+b*log(dba))       0.6        3.6 
#> 10 exp(a+b*log(dba))       0.7        2.2 
#> 11 exp(a+b*log(dba))       0.1        1.1 
#> 12 exp(a+b*log(dba))       0.4        3.3 
#> 13 exp(a+b*log(dba))       0.4       11.5 
#> 14 exp(a+b*log(dba))       0.3       11.7 
#> 15 exp(a+b*log(dba))       0.3        6.5 
#> 16 exp(a+b*log(dba))       0.5        2.6 
#> 17 a*(dba^b)               0.31       1.37
#> 18 a*(dba^b)               0.64       5.7
```

Created on 2019-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
I assume that `dbh_unit` applies not only to `dbh` but also to `dba`. Right?

**Comment by gonzalezeb** [comment]
Which diameter does dbh_min_cm refer to (in allodb)?
      The dba range (for sampled stems) as given in original publication.

Maybe I need to specify that  for each equation that uses dba. I can do it in the 'notes' column (currently called warning but I will replace the column name with notes)

**Comment by maurolepore** [comment]
> The dba range (for sampled stems) as given in original publication.

Can you please extend a bit?

Say that a single shrub has tree stems, s1, s2, and s3, with dbh values dbh1 = 1cm, dbh2 = 2cm, and dbh3 = 3cm. The resulting basal diameter (accounts for all three stems together) is this:

``` r
fgeo.biomass:::basal_diameter(c(1, 2, 3))
#> [1] 3.741657
```

Now, say that for this species of shrub, dbh_min = 3.5 cm.

Which statement is true:

a. No stem can use this equation because no stem is 3.5cm or greater.
b. All stems can use this equation because the basal diameter is greater than 3.5 cm.

**Comment by maurolepore** [comment]
For consistency, we now also distribute the biomass of shrubs which independent variable is `dbh`. This is different from what I showed in https://github.com/forestgeo/allodb/issues/41#issuecomment-479532265 (where biomass was given only for main stems).

Now, all stems (of valid `dbh` range) of each shrub have a `biomass` value that results from calculating the total biomass from the main stem and redistributing it across stems based on the contribution of each stem to the total basal area.

``` r
library(tidyverse)
library(fgeo.biomass)

shrubs <- fgeo.biomass::scbi_stem_tiny_shrub

equations <- shrubs %>%
  add_species(scbi_species, "scbi") %>%
  allo_find(dbh_unit = "mm")
#> Adding `site`.
#> Overwriting `sp`; it now stores Latin species names.
#> Adding `rowid`.
#> * Matching equations by site and species.
#> * Refining equations according to dbh.
#> * Using generic equations where expert equations can't be found.
#> Warning: Can't find equations for 38 rows (inserting `NA`).

biomass <- equations %>% 
  allo_evaluate(dbh_unit = "mm")
#> Shrub `biomass` given for main stems only but applies to the whole shrub.
#> Guessing `dbh` in [mm]
#> You may provide the `dbh` unit manually via the argument `dbh_unit`.
#> Converting `dbh` based on `dbh_unit`.
#> `biomass` values are given in [kg].

left_join(equations, biomass) %>% 
  select(treeID, sp, eqn, dbh, matches("min|max"), biomass) %>% 
  group_by(treeID) %>% 
  mutate(n = sum(!is.na(biomass))) %>% 
  filter(n > 1) %>% 
  arrange(treeID, desc(biomass)) %>% 
  select(-n) %>% 
  print(n = Inf)
#> Joining, by = "rowid"
#> # A tibble: 32 x 7
#> # Groups:   treeID [5]
#>    treeID sp           eqn               dbh dbh_min_mm dbh_max_mm  biomass
#>     <dbl> <chr>        <chr>           <dbl>      <dbl>      <dbl>    <dbl>
#>  1   2333 lindera ben~ exp(-2.2118 + ~  56.9       30        640    3.75   
#>  2   2333 lindera ben~ exp(-2.2118 + ~  55.2       30        640    3.53   
#>  3   2333 lindera ben~ <NA>             12.1       NA         NA   NA      
#>  4   2333 lindera ben~ <NA>             15.9       NA         NA   NA      
#>  5   2333 lindera ben~ <NA>             11.5       NA         NA   NA      
#>  6   2333 lindera ben~ <NA>             11.1       NA         NA   NA      
#>  7   2333 lindera ben~ <NA>             22.5       NA         NA   NA      
#>  8   2333 lindera ben~ <NA>             23.7       NA         NA   NA      
#>  9   2333 lindera ben~ <NA>             13.8       NA         NA   NA      
#> 10   2333 lindera ben~ <NA>             26         NA         NA   NA      
#> 11   2333 lindera ben~ <NA>             12         NA         NA   NA      
#> 12   2333 lindera ben~ <NA>             19.2       NA         NA   NA      
#> 13   2333 lindera ben~ <NA>             14.7       NA         NA   NA      
#> 14   3805 hamamelis v~ 38.111 * (dba^~  23.5        1.8       43.1  0.0891 
#> 15   3805 hamamelis v~ 38.111 * (dba^~  16.8        1.8       43.1  0.0127 
#> 16   3805 hamamelis v~ 38.111 * (dba^~  15.7        1.8       43.1  0.00858
#> 17   3805 hamamelis v~ 38.111 * (dba^~  15.4        1.8       43.1  0.00768
#> 18   3805 hamamelis v~ 38.111 * (dba^~  14.8        1.8       43.1  0.00610
#> 19   3805 hamamelis v~ 38.111 * (dba^~  12.7        1.8       43.1  0.00251
#> 20   3805 hamamelis v~ <NA>             94.2       NA         NA   NA      
#> 21   3805 hamamelis v~ <NA>             82.6       NA         NA   NA      
#> 22   5476 lindera ben~ exp(-2.2118 + ~  62.3       30        640    5.05   
#> 23   5476 lindera ben~ exp(-2.2118 + ~  43.7       30        640    2.49   
#> 24   5476 lindera ben~ exp(-2.2118 + ~  34.1       30        640    1.51   
#> 25   6275 hamamelis v~ 38.111 * (dba^~  42.6        1.8       43.1  1.73   
#> 26   6275 hamamelis v~ 38.111 * (dba^~  18.4        1.8       43.1  0.0133 
#> 27   6275 hamamelis v~ 38.111 * (dba^~  14.6        1.8       43.1  0.00348
#> 28   8302 hamamelis v~ 38.111 * (dba^~  16.7        1.8       43.1  0.0554 
#> 29   8302 hamamelis v~ 38.111 * (dba^~  14.9        1.8       43.1  0.0286 
#> 30   8302 hamamelis v~ 38.111 * (dba^~  10          1.8       43.1  0.00283
#> 31   8302 hamamelis v~ <NA>             51.3       NA         NA   NA      
#> 32   8302 hamamelis v~ <NA>             49         NA         NA   NA
```

Created on 2019-04-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
Here is an updated version of the [flow chart](https://drive.google.com/file/d/1HBHR4F3jkVDU9i_6s-rGdf7dWodbWYFh/view?usp=sharing)

![image](https://user-images.githubusercontent.com/5856545/55638288-d7465d80-5794-11e9-8365-63903d128b49.png)

**Comment by maurolepore** [comment]
Closing now. What remains unclear is now a separate issue

https://github.com/forestgeo/allodb/issues/86

**Comment by gonzalezeb** [comment]
Hi Mauro, I cannot see the flowchart summary here


> Here is a flowchart summary of the available code:
> 
> [`add_biomass()`](https://www.draw.io/?state=%7B%22ids%22:%5B%221HBHR4F3jkVDU9i_6s-rGdf7dWodbWYFh%22%5D,%22action%22:%22open%22,%22userId%22:%22117825629018561515109%22%7D#G1HBHR4F3jkVDU9i_6s-rGdf7dWodbWYFh)
> 
> [`add_species()` and `add_equations()`](https://www.draw.io/?libs=general;flowchart#G1MJkD7hp2XNFOYA3eMaoXgKGbOP0J3WXa)

**Comment by maurolepore** [comment]
Sorry, I hadn't made the link public. Here you go:

https://drive.google.com/file/d/1HBHR4F3jkVDU9i_6s-rGdf7dWodbWYFh/view?usp=sharing

https://drive.google.com/file/d/1MJkD7hp2XNFOYA3eMaoXgKGbOP0J3WXa/view?usp=sharing
