### ISSUE TITLE
Populate equation_id

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#47]
Follows https://github.com/forestgeo/allodb/issues/36#issuecomment-423217920.

Here is a good way to generate random ids in R: [ids::random_id()](https://richfitz.github.io/ids/vignettes/ids.html).

**Comment by maurolepore** [comment]
I understand that the unique equations that we want to identify are the unique values of `equation_allometry`, right? Until we solve this permanently, would it work if I populate `equation_id` with the values of `equation_allometry`?

**Comment by maurolepore** [comment]
After removing duplicated rows from the `equations` table, I still find that this table has more rows than unique values of `equation_allometry` (relates to #48 ). Is this expected?

``` r
library(allodb)
equations_table <- as_allodb(equations)
# Not the same:
nrow(equations_table)
#> [1] 178
length(unique(equations_table$equation_allometry))
#> [1] 147
```

Created on 2018-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by gonzalezeb** [comment]
@maurolepore Maybe we need the equation_id before I start to test the splitted tables. It is too complicated right now, specially if I want to use the same equation for multiple sites. 

I was thinking the equation_id could be something like first letter of genus+first letter of sp+number..for example, there are 4 equations for _Acer rubrum_, we could use acru_001, acru_002, acru_003, acru_004. I think equation_id should not be too long (ie. a 14 digit random number!).. so maybe the time stamp idea work best..

what do you think?

**Comment by maurolepore** [comment]
Update .csv database (233ef4c1)
