### ISSUE TITLE
In `equations`, fix row with missing values

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#50]
![image](https://user-images.githubusercontent.com/5856545/46316124-3c7a8580-c59d-11e8-9e83-ca8219f30fc6.png)

**Comment by maurolepore** [comment]
The problem comes from `master`, where a couple of rows have missing values of `equation_allometry` (and many other columns).

![image](https://user-images.githubusercontent.com/5856545/46436189-50052800-c726-11e8-8e31-4ebdfbe52bbe.png)

Given that we decided to start editing the split .csv files, the best place to fix this issue is in `data-raw/csv_database`, by removing the row where `equation_id` is "89bf40". @gonzalezeb, can you please do that?

![image](https://user-images.githubusercontent.com/5856545/46436516-fd783b80-c726-11e8-92b9-0e63655539e6.png)

**Comment by gonzalezeb** [comment]
I deleted it from both tables equation and sitespecies...

**Comment by maurolepore** [comment]
Great, thanks!

``` r
library(allodb)

equations %>% 
  filter(is.na(equation_allometry))
#> Error in equations %>% filter(is.na(equation_allometry)): could not find function "%>%"
```

Created on 2018-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)
