### ISSUE TITLE
Fix problematic equations

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#54]
The following equations have two problems:

1. They miss a parenthesis at the end ")" .
2. `AGE` can't be evaluated in terms of `DBH`. What does it mean?

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(allodb)

equations %>% 
  filter(grepl("AGE", equation_allometry)) %>% 
  select(equation_allometry, equation_id)
#> # A tibble: 2 x 2
#>   equation_allometry                                            equation_id
#>   <chr>                                                         <chr>      
#> 1 10^(3.011+1.202*(log10(DBH)-0.01(AGE)+0.011(log10(DBH)*AGE))  2a6b9b     
#> 2 10^(2.889+0.789*(log10(DBH)-0.014(AGE)+0.025(log10(DBH)*AGE)) 7901c0
```

Created on 2018-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
The following equation should have `log()` instead of `ln()`.

``` r
library(allodb)

equations %>% 
  filter(grepl("ln", equation_allometry)) %>% 
  select(equation_allometry, equation_id)
#> Error in equations %>% filter(grepl("ln", equation_allometry)) %>% select(equation_allometry, : could not find function "%>%"

DBH <- 10
exp(-0.86896+1.652882*ln(DBH))
#> Error in ln(DBH): could not find function "ln"

# See ?log
exp(-0.86896+1.652882*log(DBH))
#> [1] 18.85808
```

Created on 2018-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

![image](https://user-images.githubusercontent.com/5856545/46440174-9b243880-c730-11e8-84ca-497c605e2c1c.png)

**Comment by gonzalezeb** [comment]
I am not sure what equation to use in this package if the best available allometry for one species at one site uses stand age to calculate biomass. 
For example, two equations at Scotty Creek require stand age; maybe that's a question to @teixeirak 

| equation_allometry | equation_id|
--|--
|10^(3.011+1.202*(log10(DBH)-0.01(AGE)+0.011(log10(DBH)*AGE)) | 2a6b9b |
|10^(2.889+0.789*(log10(DBH)-0.014(AGE)+0.025(log10(DBH)*AGE))| 7901c0 |

**Comment by teixeirak** [comment]
We can't have equations requiring age. We don't have those data.

**Comment by maurolepore** [comment]
@gonzalezeb,

Can you please fix these equations? 

* Replace "DBH" with "dbh".
* Fix the unexpected `*`.

There are other problems with "dbh", "BA", and "AGE" but let's leave that for later.

``` r
library(purrr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

eval_eqn <- function(text, envir) {
  eval(parse(text = text), envir = list(dbh = 10))
}

eqn <- allodb::equations$equation_allometry
contents <- eqn %>%
  map(safely(eval_eqn)) %>%
  transpose()

bad_equations <- !map_lgl(contents$error, is.null)

fixable_equations <- allodb::equations %>% 
  filter(bad_equations) %>% 
  bind_cols(error = map_chr(contents$error[bad_equations], "message")) %>% 
  select(equation_id, equation_allometry, error) %>% 
  filter(!grepl("dba|BA|AGE", error))
fixable_equations
#> # A tibble: 9 x 3
#>   equation_id equation_allometry              error                       
#>   <chr>       <chr>                           <chr>                       
#> 1 9f4b7d      (-36.94)+0.42*(DBH^2)           object 'DBH' not found      
#> 2 da0e89      1.468+2.582*(log10((DBH-10.603~ object 'DBH' not found      
#> 3 ecef00      exp(-0.86896+1.652882*log(DBH)) object 'DBH' not found      
#> 4 e2c7c7      10^(0.15+2.48*(log10(DBH)))     object 'DBH' not found      
#> 5 686376      (-16809)+(2656.48*DBH)+248.416~ object 'DBH' not found      
#> 6 a5d599      7.06302+(-3.01775*DBH)+*(DBH^2~ "<text>:1:24: unexpected '*~
#> 7 ae60e9      36.56038+(-10.6275*DBH)+0.9383~ object 'DBH' not found      
#> 8 b47d78      1.51752+(-0.9688*DBH)+0.29833*~ object 'DBH' not found      
#> 9 a5de78      (-95.5471)+(21.1602*DBH)-1.043~ object 'DBH' not found

unique(fixable_equations$error)
#> [1] "object 'DBH' not found"                                                                
#> [2] "<text>:1:24: unexpected '*'\n1: 7.06302+(-3.01775*DBH)+*\n                           ^"
```

Created on 2018-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by gonzalezeb** [comment]
Done

**Comment by maurolepore** [comment]
@gonzalezeb, 

The equation with `equation_id = da0e89` results in `NaN`.

``` r
suppressPackageStartupMessages({
  library(tidyverse)
  library(allodb)
})

eval_eqn <- function(txt) {
  out <- eval(parse(text = txt), envir = list(dbh = 10))
  stopifnot(!is.nan(out))
}

eqn <- allodb::master() %>% 
  drop_bad_equations() %>% 
  pull("equation_allometry")



ok <- eqn %>%
  map(safely(eval_eqn)) %>%
  transpose() %>%
  pluck("error") %>%
  map_lgl(is.null)
#> Warning in eval(parse(text = txt), envir = list(dbh = 10)): NaNs produced

equations[!ok, c("equation_id", "equation_allometry")]
#> Warning: Length of logical index must be 1 or 175, not 685
#> # A tibble: 1 x 2
#>   equation_id equation_allometry
#>   <chr>       <chr>             
#> 1 <NA>        <NA>

eval(parse(text = bad$equation_allometry), envir = list(dbh = 10))
#> Error in parse(text = bad$equation_allometry): object 'bad' not found
```

Created on 2018-11-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
@gonzalezeb, these equations seem to have some kind of synax error because they err when I try to format them with `formatR::tidy_source()`:
```
"2a6b9b" "7901c0"
```

**Comment by gonzalezeb** [comment]
for equation __da0e89_   when I test it with a given dbh value I get a result   

> dbh=20 #in cm
> 1.468+2.582*(log10((dbh-10.603)/0.9823))
[1] 4.000284

but..here I wonder how a 20 cm tree will have 4kg biomass???? we will explore this later with @teixeirak

**Comment by gonzalezeb** [comment]
> @gonzalezeb, these equations seem to have some kind of synax error because they err when I try to format them with `formatR::tidy_source()`:
> 
> ```
> "2a6b9b" "7901c0"
> ```
Is this problem cause because the 'AGE"  input?

**Comment by maurolepore** [comment]
> for equation _da0e89 when I test it with a given dbh value I get a result

OK, the problem is  when `dbh <= 10.63`. Is this acceptable behaviour?

``` r
# Works
dbh <- 20
1.468 + 2.582 * (log10((dbh - 10.603) / 0.9823))
#> [1] 4.000284

# Inf
dbh <- 10.603
1.468 + 2.582 * (log10((dbh - 10.603) / 0.9823))
#> [1] -Inf

# Nan
dbh <- 10
1.468 + 2.582 * (log10((dbh - 10.603) / 0.9823))
#> Warning: NaNs produced
#> [1] NaN
```

Created on 2018-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
> Is this problem cause because the 'AGE" input?

No, the problem is that a missing trailing parenthesis:

``` r
suppressPackageStartupMessages({
  library(tidyverse)
  library(allodb)
})

eqns <- master() %>% 
  filter(equation_id %in% c("2a6b9b", "7901c0")) %>% 
  select(equation_id, equation_allometry)

# Fail
formatR::tidy_source(text = eqns$equation_allometry)
#> Error in parse(text = lines, keep.source = TRUE): <text>:2:1: unexpected numeric constant
#> 1: 10^(3.011+1.202*(log10(dbh)-0.01(AGE)+0.011(log10(dbh)*AGE))
#> 2: 10
#>    ^
styler::style_text(eqns$equation_allometry)
#> Error in parse(text = text, ...): <text>:2:1: unexpected numeric constant
#> 1: 10^(3.011+1.202*(log10(dbh)-0.01(AGE)+0.011(log10(dbh)*AGE))
#> 2: 10
#>    ^

# Pass
add_trailing_parenthesis <- sub("(.*)", "\\1)", eqns$equation_allometry)
formatR::tidy_source(text = add_trailing_parenthesis)
#> 10^(3.011 + 1.202 * (log10(dbh) - 0.01(AGE) + 0.011(log10(dbh) * AGE)))
#> 10^(2.889 + 0.789 * (log10(dbh) - 0.014(AGE) + 0.025(log10(dbh) * AGE)))
styler::style_text(add_trailing_parenthesis)
#> 10^(3.011 + 1.202 * (log10(dbh) - 0.01(AGE) + 0.011(log10(dbh) * AGE)))
#> 10^(2.889 + 0.789 * (log10(dbh) - 0.014(AGE) + 0.025(log10(dbh) * AGE)))
```

Created on 2018-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by gonzalezeb** [comment]
I fixed equation id da0e89... (the -10.603 value was wrong, the correct value is +3.033)

**Comment by teixeirak** [comment]
Is this resolved?

**Comment by maurolepore** [comment]
We lack support to calculate biomass for these equations:

``` r
library(tidyverse)
library(fgeo.biomass)

allodb::equations %>% 
  filter(equation_id %in% fixme_pull_failing_eqn(allodb::equations)) %>% 
  select(equation_id, equation_form) %>% 
  print(n = Inf)
#> # A tibble: 29 x 2
#>    equation_id equation_form                                  
#>    <chr>       <chr>                                          
#>  1 76aa3c      a*(dba^b)                                      
#>  2 28dce6      a*(dba^b)                                      
#>  3 a1646f      a*(dba^b)                                      
#>  4 b61369      a*(dba^b)                                      
#>  5 5e2dea      a*(dba^b)                                      
#>  6 3cb95a      exp(a+b*log(dba))                              
#>  7 c94845      a+b*BA                                         
#>  8 6b3b2a      exp(a+b*log(dba))                              
#>  9 b95baf      exp(a+b*log(dba))                              
#> 10 e8f868      exp(a+b*log(dba))                              
#> 11 b9b3b0      exp(a+b*log(dba))                              
#> 12 e7bf91      exp(a+b*log(dba))                              
#> 13 12104c      exp(a+b*log(dba))                              
#> 14 014bb7      exp(a+b*log(dba))                              
#> 15 604854      exp(a+b*log(dba))                              
#> 16 a1cfac      exp(a+b*log(dba))                              
#> 17 969226      exp(a+b*log(dba))                              
#> 18 2a6b9b      10^(a+b*(log10(dbh)+(c*AGE)+(d*log10(dbh)*AGE))
#> 19 7901c0      10^(a+b*(log10(dbh)+(c*AGE)+(d*log10(dbh)*AGE))
#> 20 a3a86f      a*(dba^b)                                      
#> 21 1f17bb      a*(dba^b)                                      
#> 22 c2b3e3      (dbh^a)*(h^b)*(e^c)                            
#> 23 bf5b8e      (dbh^a)*(h^b)*(e^c)                            
#> 24 448bdf      (dbh^a)*(h^b)*(e^c)                            
#> 25 c3587c      (dbh^a)*(h^b)*(e^c)                            
#> 26 becaf9      (dbh^a)*(h^b)*(e^c)                            
#> 27 99d03e      (dbh^a)*(h^b)*(e^c)                            
#> 28 12b2a9      (dbh^a)*(h^b)*(e^c)                            
#> 29 6dd993      (dbh^a)*(h^b)*(e^c)
```

Created on 2019-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by teixeirak** [comment]
I see a few categories here:
- equations calling for AGE (18,19). We cannot use these, and its difficult to foresee them ever being useful in this context. @gonzalezeb, we'll need to find alternates for these species.
- equations calling for height. These require height allometries.  @gonzalezeb, do we have corresponding height allometries?
- equation calling for BA (# 7)- @gonzalezeb, is this a shrub or tree species? If its a tree, we simply need to calculate  BA from DBH, which we already worked out, correct?
- equations calling for dba- @gonzalezeb, please clarify what dba stands for. Is that diameter at the base? 
For the latter two, some/all(?) of these equations may require calculations for shrubs (issue #41).

**Comment by gonzalezeb** [comment]
Yes. 
- yes, dba refers to stem basal diameter (clarified in the warning column in the equation table). BA
  refers to:  "_Basal area (BA)=Diameter of all stems measured 5 cm above ground in a 1x1m plot then sum to obtain basal area_". They both need to be worked with a shrub allometry discussed but not finalized in issue 41#
- I will work with the other cases..

**Comment by gonzalezeb** [comment]
I added 8 equations to estimate height for sites in Europe, 4 of them will be used in Speudelbors. 
Now we need to incorporate the equations to calculate height before biomass when necessary (in this case based on genus). I added a note in The "warning' column in the sitespecies table with a brief explanation of the eq to use.

Mauro let me know what you think.

**Comment by maurolepore** [comment]
> Now we need to incorporate the equations to calculate height before biomass when necessary 

Compared to how the BIOMASS packages calculates height, Will this be an alternative or complementary way to calculate height? Do you want to talk and explain or is it simple enough to write here?

``` r
library(BIOMASS)
data(NouraguesHD)

# If the only data available are the coordinates of your spot
NouraguesHD$lat <- 4.08
NouraguesHD$long <- -52.68
H <- retrieveH(D = NouraguesHD$D, coord = NouraguesHD[c("long", "lat")])
str(H)
#> List of 2
#>  $ H  : num [1:1051] 14.9 15 42.5 17.5 28.5 ...
#>  $ RSE: num 0.243

# If the only data available is the region of your spot
H <- retrieveH(D = NouraguesHD$D, region = "GuianaShield")
str(H)
#> List of 2
#>  $ H  : num [1:1051] 14.9 15 40.1 18.1 30.8 ...
#>  $ RSE: num 5.29

# If any height model is available
model <- modelHD(D = NouraguesHD$D, H = NouraguesHD$H, method = "log2")
H <- retrieveH(D = NouraguesHD$D, model = model)
str(H)
#> List of 2
#>  $ H  : num [1:1051] 15.2 15.3 37.7 17.9 28.1 ...
#>  $ RSE: num 4.22
```

Created on 2019-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
Following up on my previous message, I'm wrapping the BIOMASS packages to provide an interface consistent with all other functions in the __fgeo__ package-ecosystem (i.e. consistent with the tidyverse).

The examples below compute height internally, based on the region or coordinates (as above). Do you we need to expose a function that outputs height? When would this be useful?

``` r
library(fgeo.biomass)

data <- fgeo.biomass::scbi_stem_tiny_tree
species <- fgeo.biomass::scbi_species

add_tropical_biomass(data, species, region = "pantropical")
#> Guessing `dbh` in [mm].
#> You may provide the `dbh` unit manually via the argument `dbh_unit`.
#> Wood density given in [g/cm^3].
#> Biomass is given in [kg].
#> Adding new columns:
#> 'family', 'genus', 'species', 'wd_level', 'wd_mean', 'wd_sd', 'biomass'
#> # A tibble: 11 x 27
#>    treeID stemID    tag StemTag sp    quadrat    gx    gy DBHID CensusID
#>     <dbl>  <dbl>  <dbl>   <dbl> <chr> <chr>   <dbl> <dbl> <dbl>    <dbl>
#>  1   3175   3175  22146       1 caca  0221     29    404.  6103        1
#>  2   3175  32574  22146       2 caca  0221     29    404.  6104        1
#>  3   3996   3996  30363       1 litu  0307     50.3  139.  7096        1
#>  4   3996  32682  30363       2 litu  0307     50.3  139.  7097        1
#>  5   5570   5570  42082       1 caca  0419     71.3  363.  9047        1
#>  6   5570  32894  42082       2 caca  0419     71.3  363.  9048        1
#>  7   5570  37222  42082       3 caca  0419     71.3  363.  9049        1
#>  8  10060  10060  82218       1 litu  0822    159.   436  14579        1
#>  9  10060  33449  82218       2 litu  0822    159.   436  14580        1
#> 10  26760  26760 180969       1 ulru  1812    350.   227. 34958        1
#> 11  26760  35964 180969       2 ulru  1812    350.   227. 34959        1
#> # ... with 17 more variables: dbh <dbl>, pom <dbl>, hom <dbl>,
#> #   ExactDate <date>, DFstatus <chr>, codes <chr>, countPOM <dbl>,
#> #   date <dbl>, status <chr>, agb <dbl>, family <chr>, genus <chr>,
#> #   species <chr>, wd_level <chr>, wd_mean <dbl>, wd_sd <dbl>,
#> #   biomass <dbl>

add_tropical_biomass(data, species, latitude = -34, longitude = -58)
#> Guessing `dbh` in [mm].
#> You may provide the `dbh` unit manually via the argument `dbh_unit`.
#> Wood density given in [g/cm^3].
#> Ignoring `region` and using `latitude` and `longitude`.
#> Biomass is given in [kg].
#> Adding new columns:
#> 'family', 'genus', 'species', 'wd_level', 'wd_mean', 'wd_sd', 'latitude', 'longitude', 'biomass'
#> # A tibble: 11 x 29
#>    treeID stemID    tag StemTag sp    quadrat    gx    gy DBHID CensusID
#>     <dbl>  <dbl>  <dbl>   <dbl> <chr> <chr>   <dbl> <dbl> <dbl>    <dbl>
#>  1   3175   3175  22146       1 caca  0221     29    404.  6103        1
#>  2   3175  32574  22146       2 caca  0221     29    404.  6104        1
#>  3   3996   3996  30363       1 litu  0307     50.3  139.  7096        1
#>  4   3996  32682  30363       2 litu  0307     50.3  139.  7097        1
#>  5   5570   5570  42082       1 caca  0419     71.3  363.  9047        1
#>  6   5570  32894  42082       2 caca  0419     71.3  363.  9048        1
#>  7   5570  37222  42082       3 caca  0419     71.3  363.  9049        1
#>  8  10060  10060  82218       1 litu  0822    159.   436  14579        1
#>  9  10060  33449  82218       2 litu  0822    159.   436  14580        1
#> 10  26760  26760 180969       1 ulru  1812    350.   227. 34958        1
#> 11  26760  35964 180969       2 ulru  1812    350.   227. 34959        1
#> # ... with 19 more variables: dbh <dbl>, pom <dbl>, hom <dbl>,
#> #   ExactDate <date>, DFstatus <chr>, codes <chr>, countPOM <dbl>,
#> #   date <dbl>, status <chr>, agb <dbl>, family <chr>, genus <chr>,
#> #   species <chr>, wd_level <chr>, wd_mean <dbl>, wd_sd <dbl>,
#> #   latitude <dbl>, longitude <dbl>, biomass <dbl>
```

Created on 2019-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by gonzalezeb** [comment]
> Compared to how the BIOMASS packages calculates height, Will this be an alternative or complementary way to calculate height?

- For temperate sites, in particular, we will select height allometries (either site specific, from similar areas or generic/regional) as the modelHD function in BIOMASS is for the tropics. For example, in the case of Speldeurbos where the biomass equations for all species require tree height we will use the height allometries given in the eq table. It would require a similar function as allo_evaluate to be applied before calculating the biomass.

**Comment by maurolepore** [comment]
Let me make a distinction between estimating height when the user doesn't provide it, versus computing biomass using height as one input parameter (in addition to dbh).

The BIOMASS package provides a way to estimate height based on a `region` name or based on `latitude` and `longitude` coordinates. I have aready wrapped this features in fgeo.biomass (not yet merged into master). But I understand that this is appropriate only for tropical species. Do you know of any means to estimate height for temperate species? Or do you feel comfortable estimating height with Chave's method for tropical species?

Once we have biomass, either estimated or given by the user, then the code can certanly look up the value of height and use it in an equation to compute biomass. I haven't done this yet, but it is a relatively simple task.

**Comment by teixeirak** [comment]
@maurolepore, 

REGARDING BIOMASS PACKAGE/ TROPICAL SITES: 
1. The BIOMASS package should only be applied in the tropics (or maybe some subtropical sites). 
2. When using BIOMASS, height is estimated based on region or location, as you note. This is great for sites that don't have  site-specific height allometries/measurements. However, some sites have developed these (e.g., BCI), which is the ideal.
3. When a BIOMASS user enters height data (along with DBH/ census data), the code creates height allometries on the fly, and uses associated error as part of the error propagation process. However, the typical scenario for our user community would be that height measurements have been made some point and used to develop allometric equations for height (as opposed to measuring height as part of a census). This creates a problem for using BIOMASS at a site for which we have developed a site-specific height allometry. 
4. To get around this, we could first use our height allometry to estimate height for all trees, then feed those calculated heights into BIOMASS. The problem with this is that BIOMASS will see a perfect relationship between DBH and height, and error will be underestimated. Therefore, in these cases we need to throw a warning that BIOMASS is underestimating error ...
5. If/when we get to the point of error propagation in our own code (#75), we'll probably need to re-create the process used in BIOMASS so that we can get proper error propagation.

**Comment by teixeirak** [comment]
REGARDING TEMPERATE SITES:
When there is both (1) a height allometry and (2) a biomass allometry that takes height as input, the code should first calculate height and then use that as input to the biomass allometry. Both equations will be stored in the equations table. @gonzalezeb can explain if this is confusing.

**Comment by maurolepore** [comment]
Good, the comment above helps me understand that what you mean by 'height allometry' is the equation to estimate height from dbh. I was confused, and thought that you meant the biomass equations that depend not only on dbh but also on height. Thanks!

**Comment by ervanSTRI** [comment]
Just read part of your discussion here, and I might have missed prior/further messages, but the Biomass package allows to fit local Weibull functions on a few height measurments (and get a local H-D function with associate error). For prescriptions about minimum sample size to estimate H-D relationships, you can refer to Sulivan et al. 2018. HTH
