### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#55]
Following a meeting with @gonzalezeb I plan to add these tests:

- [ ] In `equations`, `equation_id` has no duplicated values.
- [ ] In `equations`, `equation_allometry` has no duplicated values.

Other pendent tests:

- [ ] In `equations`, after excluding `equation_id`, no row is full of missing values.
- [ ] `master()`.

**Comment by gonzalezeb** [comment]
test have been added for every function
