### ISSUE TITLE
Reference table

### ISSUE THREAD

**Issue by gonzalezeb** [forestgeo/allodb#57]
I cannot find the reference table, I see the reference_metadata in csv_database. I though I kept that table there, where I would feed the reference data (citation) for each equation.

But I just realized a big mistake. In the equations table we have a 'ref_id' but I never gave an id to each reference (each row) in the reference table (now lost).

I think I need help from @maurolepore

**Comment by maurolepore** [comment]
@gonzalezeb, can you find the last commit where the table you need is still there?

https://github.com/forestgeo/allodb/commits/master

**Comment by gonzalezeb** [comment]
The second commit below

![image](https://user-images.githubusercontent.com/26872628/46976907-b2501800-d098-11e8-994e-288d81b76e56.png)

**Comment by gonzalezeb** [comment]
commit 3a8d5b8c711fd602ba807fe69a001eb489b5a7f2

**Comment by maurolepore** [comment]
This is how I rescued references.csv:

```bash
git checkout 3a8d5b8c711fd602ba807fe69a001eb489b5a7f2
```

Manually copy the file into another folder

```bash
git checkout master
```

Manually paste the file into data-raw/

**Comment by maurolepore** [comment]
Now we are still left with the problem of linking id to references, right?

Can you please find a commit where there is a master table that contains the references and `equation_allometry`? I think I could match `equation_allometry` to try find the id.

**Comment by gonzalezeb** [comment]
This  commit f8962bc4ce00c625fe20183c93184a1f5904240c seems to be the last where the master table and equation_allometry where together..

But the real problem is that I never gave a ref_id. I think my idea was to use something like: first 4 letter of lastname then year, i.e. Clar_1985 (I prefer this way to numbers). Maybe I have to do that by hand?

**Comment by maurolepore** [comment]
OK, thanks! I'll have a look tomorrow.

**Comment by gonzalezeb** [comment]
To your question: What will happen if two equations have the same combination of author and year?
Let's use Krista's system on a previous pub as citation or reference ID:
>Citation ID in the form [last name of first author]_[year]_[first letter of first four words of title, 
when applicable]. 

The final reference table should have the following columns:

| ref.id | ref.doi | ref.author | ref.year | ref.title | ref.journal |
| -- | -- | -- | -- | -- | -- |

**Comment by maurolepore** [comment]
@gonzalezeb 

I updated data-raw/data_references_id.csv to reflect your request. You'll need to check the data, remove `ref_id`, then rename `refid` as `ref_id`.

Let me know your questions.

![image](https://user-images.githubusercontent.com/5856545/47184839-bfb80d00-d2f9-11e8-8336-32c28a5612a2.png)

**Comment by maurolepore** [comment]
@gonzalezeb, the problem is that this new id doesn't help in linking the equations table with the references table -- which is what we wanted in the first place. That is because the `master` table we recovered has no information about reference title. It only has `biomass_equation_source` which contains author and year.

I think I could use `author_year` once, as I was doing before, to first link the two tables, i.e. references and equation. Then create a reference id formatted as you requested and use that format from then on.

**Comment by maurolepore** [comment]
@gonzalezeb, I believe this closes this issue: https://github.com/forestgeo/allodb/blob/master/inst/issues/57.md

![image](https://user-images.githubusercontent.com/5856545/47240692-336c1f80-d3b7-11e8-8d17-4d38d537eeac.png)
