### ISSUE TITLE
Set up trial runs of allo-db

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#58]
Let's set up trial runs of allodb on census data. I recommend starting with SCBI and BCI because they provide examples of tropical and temperate sites, and data are fully open access.

**Comment by maurolepore** [comment]
@teixeirak, I have data from BCI and Luquillo (which is better structured). Could you share with me the data from SCBI that you'd like to use? For convenience, I'll put it in a package. The natural place to live would be either on its own package or as part of [fgeo.data__](https://forestgeo.github.io/fgeo.data/). Let me know if this works for you and what's your preferred option.

**Comment by gonzalezeb** [comment]
I just uploaded into allodb/data-raw the R table for census 1 at SCBI:  `stem.table.1`

**Comment by maurolepore** [comment]
RE https://github.com/forestgeo/allodb/issues/58#issuecomment-431150941 I added the data to data/. Please document it in R/data.R.

**Comment by maurolepore** [comment]
@teixeirak, re the data:

* Data from SCBI now lives in __allodb__ but if you are OK I would like to eventually move it to __fgeo.data__.

WARNING: 

Internally, I can access many more datasets than those I can share publicly.

* Data from BCI and Luquillo live in __bciex__ (https://forestgeo.github.io/bciex/) and __fgeo.data__, respectively. These datasets are OK for examples and tests but not for research -- they are real data but only tiny datasets. 

If you want complete datasets you should talk to Stuart and Suzanne. Even when those data are public I have been authorized to use only subsets of data for public uses.

**Comment by teixeirak** [comment]
I'd like to stick with data that's public so that we can have in in the public allodb repo, and eventually possibly include examples in our data pub. SCBI data are fully public. You're welcome to put it in fgeo.data, with the understanding that the master is still the one in the database.

**Comment by maurolepore** [comment]
>  You're welcome to put it in fgeo.data, with the understanding that the master is still the one in the database.

Great! The way I usually manage different versions of data is this:

* Each site gets its own package. That's the place to keep the data up to date. I keep this package and its associated GitHub repo _private_.

* If the PI authorizes, I use some datasets or subsets of datasets in __fgeo.data__ and any other package that needs those data.

This modular approach makes it easy to maintain the data. If you update the data, there is only one place to do it and you are free to update it as frequently as you want in the (maybe private) __scbi__ package. Then, how frequently I update the packages downstream depends on the release plan. 

The structure I suggest is therefore this:

* __scbi__ depends on nothing.
* __allodb__ uses some or all data from scbi.
* __fgeo.data__ uses some or all data from __scbi__.

Would you be happy to follow this structure? Do you think there is a better way to do it?

**Comment by teixeirak** [comment]
Actually, we've made a GitHub organization for SCBI data: https://github.com/SCBI-ForestGEO. We're going to manage that as a mix of public and private. Can you draw directly from that?

**Comment by maurolepore** [comment]
Yes, I can. I'll need access to wherever the data is stored and I'll treat the data from private repos as private and that from public repos as public.

**Comment by teixeirak** [comment]
I just added you to the organization and gave you access to the most relevant private repo at the moment. We're working on getting more data/repos added to that organization and made public.

**Comment by maurolepore** [comment]
Thanks! FYI, I don't see a repo yet with the dataset scbi.stem1.rdata. I don't need the file as it's already in __allodb__; but one nice outcome of this thread -- I believe -- would be to know where to point as the source of scbi.stem1.rdata (even it that is a priveta repo).

Also FYI, I like making my name appear publicly to show the world what kind of projects I'm part of. You may want to do that too.


![image](https://user-images.githubusercontent.com/5856545/47237445-1cc0cb00-d3ad-11e8-816d-6f52737c8212.png)

**Comment by teixeirak** [comment]
Thanks for the tip on making memberships public; I wasn't aware.

Regarding the data, what is your understanding with Stuart about the relationship between the census data on GitHub and in the ForestGEO database? The data are public, but we want a clear master.

**Comment by maurolepore** [comment]
> Regarding the data, what is your understanding with Stuart about the relationship between the census data on GitHub and in the ForestGEO database?

I'm not sure. The data I host are just subsets of data, not for research but for demos. Stuart has been OK with that.

**Comment by gonzalezeb** [comment]
Public data for census 1 at SCBI now resides [here](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_core_census/README.md)

**Comment by teixeirak** [comment]
Thanks @gonzalezeb!
@maurolepore, what do we now need for a trial run?

**Comment by maurolepore** [comment]
@gonzalezeb, FYI the link above fails. I think the link is now https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_main_census/README.md

@teixeirak, I think we are good to go. I'm busy right now getting ready for a review of __fgeo__ tomorrow. Next week I should be able to add this scbi data to __fgeo.data__ and resume work on __bmss__ and __alldb__, aiming to run the trial you are asking for.

**Comment by maurolepore** [comment]
This issue has branched and I'm getting confused. I'll close this one now and follow on #36.
