### ISSUE TITLE
Structure allo-db to ensure that biomass is calculated based off clean data

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#59]
Following up on conversation with Stuart yesterday,

We need to ensure that allo-db is not presented as sufficient in and of itself to get good biomass values, as there's potential for misuse. The dbh that goes in needs to be cleaned (e.g., dealing with data errors) and taper-corrected when measured above buttresses. Thus, it should be presented as one module in a larger biomass calculation package, also including code from @ervanSTRI.

@gonzalezeb and I need to make sure this is clearly presented in the data pub. @maurolepore, please ensure that the R code is structured appropriately.

**Comment by maurolepore** [comment]
Good. I think the best place to explain that in __allodb__ is in its REAME. That'a the place to not only show what a package does but also how it relates to other projects. We could provide links. 

Also, once all modules are ready, they all will likely be nested inside the meta package __fgeo__. There, a vignette could show with examples how the different modules relate to each other.

**Comment by teixeirak** [comment]
Our plans will solve this, so I will close this issue.
