### ISSUE TITLE
Tropical: Add to biomass() a parameter to input wood density 

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#6]
Ervan suggests that the biomass() function needs a parameter to input wood density because new wood density data becomes available frequently and users may want to incorporate it. That is why he prefers to compute biomass not with a fixed equation but as a function of wood density.

**Comment by gonzalezeb** [comment]
To close this issue, I will do the following:

- update the current wsg table in allodb. It will include all ForestGEO sites with public species list. 
I proposed this so there is a WD table in allodb that can be sourced when needed by fgeo.biomass. 
Please @teixeirak need to confirm if this is correct. 

- use the gewWodDensity function from BIOMASS to get values from Zanne et al 2009 for all species in our list.
- incorporate WD values contributed from PI' (Joe W: Yasuni-Panama-Pasoh; Diego Rodriguez: Heishiding)

**Comment by teixeirak** [comment]
Two questions here:
1- structurally, do we want to include all these species in the site-species table, then link to the WD table? I think that was the original plan.
2- Do we gain much by retrieving those values now? We gain some speed, but I believe BIOMASS uses data from the wood density database to estimate uncertainty.
3- Also, if we retrieve wood density values now, we would need to ensure that they get overridden when new values are added to the database.

All together, maybe just include wood density values that we have specifically for ForestGEO sites, at least for now?

**Comment by gonzalezeb** [comment]
Closing issue because we no longer work with tropical allometries
