### ISSUE TITLE
ensure clear structure for users of allo-db to modify allometric equation choices

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#60]
It will be important to work out a clear mechanism for advanced users of allo-db to modify choices of allometric equations. This could be done permanently, with approval of allo-db managers, through alteration of the master sites-species table (e.g., if a site PI identifies a more appropriate equation). However, I'm not sure we have a mechanism for temporary modification (e.g., if someone wants to compare results of using different equations). @maurolepore, can you please find a way to make this possible through the code?

**Comment by maurolepore** [comment]
> I'm not sure we have a mechanism for temporary modification (e.g., if someone wants to compare results of using different equations). @maurolepore, can you please find a way to make this possible through the code?

I'll keep this in mind. For every decision the code does we can let users overwrite the default. Stuart and I touched on this topic yesterday. He wanted to know more about where the Wood Density Data was coming from and how a user could change that. Using that as an example, the code could use whatever table __allodb__ provides, but allow the user to use a custom table instead.

**Comment by maurolepore** [comment]
> It will be important to work out a clear mechanism for advanced users of allo-db to modify choices of allometric equations. This could be done permanently, with approval of allo-db managers, through alteration of the master sites-species table (e.g., if a site PI identifies a more appropriate equation).

Users can now choose a focused issue to propose a more appropriate equation at https://github.com/forestgeo/allodb/issues/new/choose

This issue will be automatically assigned to @gonzalezeb and @teixeirak, and will be labeled as 'enhancement'. You can edit/create template at https://github.com/forestgeo/allodb/issues/templates/edit

**Comment by teixeirak** [comment]
Thanks for setting this up! I'll let @gonzalezeb set up the template-- should be simple, but we need to make sure it includes all the necessary info to populate the table.

**Comment by maurolepore** [comment]
> I'm not sure we have a mechanism for temporary modification (e.g., if someone wants to compare results of using different equations). @maurolepore, can you please find a way to make this possible through the code?

`allo_find()` gains the argument `custom_eqn`. Defaults to using default equations (i.e. `custom_eqn = NULL`).

``` r
library(fgeo.biomass)

# `as_eqn()` checks that the structure of your data isn't terriby wrong
as_eqn("really bad data")
#> Error in validate_eqn(data): is.data.frame(data) is not TRUE
as_eqn(data.frame(1))
#> Error: Ensure your data set has these variables:
#> equation_id, site, sp, eqn, eqn_type, anatomic_relevance

your_equations <- tibble::tibble(
  equation_id = c("000001"),
  site = c("scbi"),
  sp = c("paulownia tomentosa"),
  eqn = c("exp(-2.48 + 2.4835 * log(dbh))"),
  eqn_type = c("mixed_hardwood"),
  anatomic_relevance = c("total aboveground biomass")
)

class(as_eqn(your_equations))
#> [1] "eqn"        "tbl_df"     "tbl"        "data.frame"

census <- fgeo.biomass::scbi_tree1
species <- fgeo.biomass::scbi_species
dbh_species <- add_species(
  census, species,
  site = "scbi"
)

# Default equations
allo_find(dbh_species)
#> # A tibble: 5 x 2
#>   eqn_type       data                 
#>   <chr>          <list>               
#> 1 species        <tibble [8,930 x 8]> 
#> 2 genus          <tibble [5,642 x 8]> 
#> 3 mixed_hardwood <tibble [5,516 x 8]> 
#> 4 family         <tibble [10,141 x 8]>
#> 5 woody_species  <tibble [0 x 8]>

# Custom equations
allo_find(dbh_species, custom_eqn = as_eqn(your_equations))
#> # A tibble: 1 x 2
#>   eqn_type       data            
#>   <chr>          <list>          
#> 1 mixed_hardwood <tibble [3 x 8]>

dbh_species %>%
  allo_find(custom_eqn = as_eqn(your_equations)) %>%
  allo_order() %>%
  allo_evaluate()
#> # A tibble: 3 x 10
#>   eqn_type rowid site  sp      dbh equation_id eqn   eqn_source
#>   <chr>    <int> <chr> <chr> <dbl> <chr>       <chr> <chr>     
#> 1 mixed_h~  9645 scbi  paul~  462. 000001      exp(~ custom    
#> 2 mixed_h~ 10838 scbi  paul~  363. 000001      exp(~ custom    
#> 3 mixed_h~ 10842 scbi  paul~  531. 000001      exp(~ custom    
#> # ... with 2 more variables: anatomic_relevance <chr>, biomass <dbl>
```

Created on 2019-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by gonzalezeb** [comment]
This idea is somehow covered by the [new_equations](v) function.
