### ISSUE TITLE
Sum biomass across the multiple components of a single tree

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#63]
@gonzalezeb, 

Is there a way to decide what equation to pick when multiple equations are available for the same species, site, and specificity?

``` r
suppressPackageStartupMessages({
  
  library(tidyverse)
  library(allodb)
})

master() %>%
  select(site, species, allometry_specificity, equation_allometry) %>% 
  filter(complete.cases(.)) %>% 
  unique() %>% 
  add_count(site, species, sort = TRUE) %>% 
  filter(n > 1)
#> # A tibble: 165 x 5
#>    site    species     allometry_specifi~ equation_allometry             n
#>    <chr>   <chr>       <chr>              <chr>                      <int>
#>  1 Yosemi~ Abies conc~ Species            exp(2.7261+2.3324*log(dbh~     5
#>  2 Yosemi~ Abies conc~ Species            exp(2.03496+2.1683*log(db~     5
#>  3 Yosemi~ Abies conc~ Species            exp(3.892752+2.5812*log(d~     5
#>  4 Yosemi~ Abies conc~ Species            exp(-10.8036+2.7727*dbh+1~     5
#>  5 Yosemi~ Abies conc~ Species            exp(4.36982+2.5043*log(db~     5
#>  6 Utah    Pinus flex~ Species            10^(-1.024+2.416*(log10(d~     5
#>  7 Utah    Pinus long~ Species            10^(-1.024+2.416*(log10(d~     5
#>  8 Utah    Pinus flex~ Species            10^(-1.234+2.128*(log10(d~     5
#>  9 Utah    Pinus long~ Species            10^(-1.234+2.128*(log10(d~     5
#> 10 Utah    Pinus flex~ Species            10^(-2.336+2.650*(log10(d~     5
#> # ... with 155 more rows
```

Created on 2018-11-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
Great! I expected that some variable would encode the solution (i.e. `dependent_variable_biomass_component `) but I couldn't figure out which one. Right now the code ignores this and cuts corners to deal with it. But surely your suggestion will be incorporated.  Thanks!

**Comment by maurolepore** [comment]
> We need something in the code that said: IF _dependent_variable_biomass_component_ is not "Whole tree" or "Total aboveground biomass" them sum all components given

@gonzalezeb, 

Based on your comment, I expec `rowid` to be unique where `anatomic_relevance` (for short) matches "whole tree" or "total above ground biomass". But the code below still show duplicates. What's the best way to solve this?

``` r
# Duplicated `rowid` where `anatomic_relevance` is "whole tree ..."
# How is "above stump" different from "above and belowground"?

suppressPackageStartupMessages(library(fgeo.biomass))
suppressPackageStartupMessages(library(dplyr))

best <- fgeo.biomass::scbi_tree1 %>%
  add_species(fgeo.biomass::scbi_species, "scbi") %>%
  allo_find() %>%
  allo_order()

best %>%
  fixme_find_duplicated_rowid() %>% 
  right_join(best) %>% 
  filter(!is.na(n)) %>% 
  filter(grepl("whole tree|total aboveground biomass", anatomic_relevance)) %>% 
  select(rowid, sp, equation_id, anatomic_relevance, n)
#> Joining, by = c("eqn_type", "rowid", "site", "sp", "dbh", "equation_id", "eqn", "eqn_source", "anatomic_relevance")
#> # A tibble: 694 x 5
#>    rowid sp              equation_id anatomic_relevance                   n
#>    <int> <chr>           <chr>       <chr>                            <int>
#>  1   897 quercus veluti~ 7640f0      whole tree (above stump)             2
#>  2   897 quercus veluti~ c70dea      whole tree (above and belowgrou~     2
#>  3  1465 quercus veluti~ 7640f0      whole tree (above stump)             2
#>  4  1465 quercus veluti~ c70dea      whole tree (above and belowgrou~     2
#>  5  1474 quercus veluti~ 7640f0      whole tree (above stump)             2
#>  6  1474 quercus veluti~ c70dea      whole tree (above and belowgrou~     2
#>  7  1626 quercus veluti~ 7640f0      whole tree (above stump)             2
#>  8  1626 quercus veluti~ c70dea      whole tree (above and belowgrou~     2
#>  9  1634 quercus veluti~ 7640f0      whole tree (above stump)             2
#> 10  1634 quercus veluti~ c70dea      whole tree (above and belowgrou~     2
#> # ... with 684 more rows
```

Created on 2019-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by maurolepore** [comment]
FYI, I changed the temporary approach to overcome this issue. Before I was removing all duplicates except one. Now I'm dropping all rows where `rowid` isn't unique across the entire dataset. This is more exteeme but also more conservative -- in case someone doesn't pay enough attention to the warning saying that the fgeo.biomass package is in an experimental stage of development.

https://forestgeo.github.io/fgeo.biomass/#known-issues

**Comment by gonzalezeb** [comment]
To remember: 
-handle dbh ranges first (i.e. before sumarizing values)
-more conservative will be to chose equations with dbh ranges where the dbh_min is slyly higher that the current stem dbh (kind of)

**Comment by gonzalezeb** [comment]
More on what could happen when a stem doesn't fit into an equation dbh range
If stem dbh falls in range -> use respective equation
If stem dbh is less than the minimum dbh given by any equation -> use the closest equation in range
If stem dhb is outside range use the closest to highest range (because of stem growth)..

**Comment by teixeirak** [comment]
There are two cases here that require special consideration:
1- In case the equation falls within range of two equations (we saw an example for PSME), use the equation with the higher DBH range.
2- If the stem DBH is higher than the upper DBH limit, we have a problem, as extrapolating far outside the range of allometries can lead to really large errors. I just opened a separate issue on this (#69).

**Comment by maurolepore** [comment]
Just renamed the title to more clearly reflect the goal of this issue. The original title suggested that the code should pick one equation per tree and then calculate biomass. Instead, it is now clear that the issue is not before but after calculating biomass. The issue is to group rows by tree and then summarize the biomass by summing the potentially multiple rows.
