### ISSUE TITLE
Determine how to interact with BIOMASS package

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#67]
Determine how our package interacts with/ sources the [BIOMASS package](https://cran.r-project.org/web/packages/BIOMASS/index.html).

Requirements/ Goals:
1- Our code should give the same answer as BIOMASS, and we need assurance that this is maintained as both packages change
2- fgeo users should experience a simple, smoothly integrated, unified process for computing biomass. They should not have to separately load and interact with BIOMASS or give separate treatment to sites using allodb equations tables vs BIOMASS package.

Two main options:
1- Put fgeo wrapper around BIOMASS
2- Use pieces of BIOMASS code in our package

**Comment by maurolepore** [comment]
For the record, the two most clear features we want from BIOMASS are these:

* Ability to calculate biomass when allodb has no way to calculate it.
* Ability to propagate errors.

**Comment by teixeirak** [comment]
My current vision for how the BIOMASS package should fit in is in the diagram I just added under issue #68.
In words, the basic process would be:
1. fgeo.biomass passes site, sp, dbh to allodb's site/species table. This determines whether we have any site/species specific information (equation, wood density data, or height data/allometry).
2. For tropical species with no site/ species-specific equation, data [site (with lat-long), species, dbh, WD, if available, height*(if available)] then get passed to BIOMASS.
3. Biomass is calculated either in allodb based on equations or in BIOMASS*. Biomass estimates are returned to fgeo.biomass for further calculations (e.g., individual growth, ecosystem biomass or productivity).


@maurolepore, please confirm that this scheme makes sense from a technical/coding perspective. I see two issues in particular that may present problems:
1-  *There's a potential incompatibility with BIOMASS when it comes to the approach is in the handling of height allometries. Some of our sites have height allometries, which are to be included in our equations table. However, the BIOMASS package uses raw height data to calculate an allometry. I do not know that we can pass it an equation. Alternatively, we could easily put the equation in our table and calculate values for those species within allodb. @maurolepore, this will be something for you to look into.
2- The other issue is speed/ efficiency. Will loading and calling the BIOMASS package make the process much slower/ more difficult for fgeo.biomass users?

**Comment by maurolepore** [comment]
> My current vision for how the BIOMASS package should fit in is in the diagram I just added under issue #68 ...

Please see #68 to see how your vision and mine compre. In summary, fgeo.biomass is the only interface that users need. It contains all computation and logic, and uses allodb and BIOMASS internally, as needed.

**Comment by maurolepore** [comment]
> 2. The other issue is speed/ efficiency. Will loading and calling the BIOMASS package make the process much slower/ more difficult for fgeo.biomass users?

See https://github.com/forestgeo/allodb/issues/76

> 1. There's a potential incompatibility with BIOMASS when it comes to the approach is in the handling of height allometries.

See https://github.com/forestgeo/allodb/issues/19

**Comment by teixeirak** [comment]
I'd treat the height data issue as separate from issue #19. Issue #19 is about how we store and handle height allometries within allodb. Here, I'm asking if there's a way to pass these allometries to BIOMASS, or do we need some work-around.

Note that this isn't the highest priority at the moment (not necessary to ensure basic functionality, but to improve predictions for a subset of sites), but I want to ensure that the overall structure will be robust when we get around to adding this.

Regarding speed/efficiency, your comment in issue #76 makes sense.

**Comment by teixeirak** [comment]
More specifics regarding height allometries:

The biomass package doesn't seem to have any function whereby you can pass it a height equation. Rather, it wants RAW DATA (i.e., measurement of DBH together with height for the trees on which you want to calculate biomass). We do not store height data in the ForestGEO census data tables, and therefore we don't have that available to pass to BIOMASS. As a result, we might not be able to take advantage of our site-specific height allometries when using the BIOMASS package.

**Comment by teixeirak** [comment]
This issue as a whole is high priority, but I believe we've got it mostly figured out. The remaining challenge is to determine whether we will somehow pass site-specific allometries to BIOMASS or whether we'll put the equations in allodb. @maurolepore, I believe the next step will be for you to examine the structure of the code.

**Comment by maurolepore** [comment]
I've been playing with BIOMASS. I now plan to wrap the most important features, as shown in the flowchart below. Wrapping BIOMASS is important to provide users with interfaces that play well with fgeo and all other tidyverse-friendly packages.

https://www.draw.io/#G15J7MgV7ZN-uCI9drxfYyutockcUvaWQI

![image](https://user-images.githubusercontent.com/5856545/55984576-c8b3e680-5c6b-11e9-84d6-a11f4a0f240c.png)

**Comment by maurolepore** [comment]
FYI, fgeo.biomass now incorporates what I believe are the most useful feature of BIOMASS (green arrows in the flowchart above). [Here](https://forestgeo.github.io/fgeo.biomass/#biomass-via-biomass-versus-allodb) you can see fgeo.biomass behaves when internally using allodb versus BIOMASS. At first glance the biomass values from both frameworks seem to overlap.

**Comment by gonzalezeb** [comment]
Closing issue because allodb scope changed.
