### ISSUE TITLE
Missmatching values of 'site'

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#79]
@gonzalezeb, I noticed that the values of `site` are different in `sitespecies` versus `sites_info` tables.

I see a difference in upper versus lower case, and also in some strings, e.g.   "Lilly Dicky" versus   "lilly dickey woods".

This missmatch will result in missing values in the output of `master()`, and where the difference is not only of of "case" it will result in information loss.

For now, I should be able to fix this with code and move on. But you may want to do the fix in the csv database.

```R

# `sitespecies`:
  
c(
  "Lilly Dicky",
  "SCBI",
  "SERC",
  "Tyson",
  "UCSC",
  "Wabikon",
  "Wind River",
  "Wytham Woods",
  "Yosemite",
  "Zofin",
  "Utah",
  "UMBC",
  "Harvard Forest",
  "Scotty Creek",
  "Michigan Big Woods",
  "Traunstein",
  "Speulderbos"
)

# `sites_info`:
  
c(
  "amacayacu",
  "badagongshan",
  "baotianman",
  "barro colorado island",
  "bukit timah",
  "changbaishan",
  "cocoli",
  "danum valley",
  "dinghushan",
  "doi inthanon",
  "donglingshan",
  "fushan",
  "gutianshan",
  "haliburton",
  "harvard forest",
  "heishiding",
  "hong kong",
  "huai kha khaeng",
  "ilha do cardoso",
  "ituri average (edoro & lenda)",
  "ituri-edoro1",
  "ituri-edoro2",
  "ituri-lenda1",
  "ituri-lenda2",
  "jianfengling",
  "kenting",
  "khao chong",
  "korup",
  "kuala belalong",
  "la planada",
  "lambir",
  "laupahoehoe",
  "lienhuachih",
  "lilly dickey woods",
  "luquillo",
  "manaus",
  "mo singto",
  "mpala",
  "mudumalai",
  "nanjenshan",
  "nonggang",
  "palamanui",
  "palanan",
  "pasoh",
  "rabi",
  "san lorenzo/ sherman",
  "santa cruz",
  "scbi",
  "scotty creek",
  "serc",
  "sinharaja",
  "speulderbos",
  "tiantongshan",
  "tyson research center",
  "wabikon",
  "wanang",
  "wind river",
  "wytham woods",
  "xishuangbanna",
  "yasuni",
  "yosemite national park",
  "zenlun",
  "zofin"
)
```

**Comment by maurolepore** [comment]
@gonzalezeb,

I'm now inclined to not do this in code and instead ask you to do it on the .csv database. This requires making a bold decision about two different site names referring to the same actual site -- a decision that you are more able to do than me.

This is an important issue as `site` is the _key_ linking the `sitespecies` and `sites_info` tables. It's not urgent not because we are working with an example from SCBI, which site name matches okay. But for the sites with missmatching names, the problem would manifest itself in the form of missing values everywhere.

This code should help you find the problematic site names.

``` r
in_sitespecies <- tolower(sort(unique(allodb::sitespecies$site)))
in_sites_info <- tolower(sort(unique(allodb::sites_info$site)))

# Sites in in `sitesspecies` that don't match sites in `sites_info`
setdiff(in_sitespecies, in_sites_info)
#> [1] "lilly dicky"        "michigan big woods" "traunstein"        
#> [4] "tyson"              "ucsc"               "umbc"              
#> [7] "utah"               "yosemite"

# Lookup here for similar names and edit them so they match exactly 
in_sites_info
#>  [1] "amacayacu"                     "badagongshan"                 
#>  [3] "baotianman"                    "barro colorado island"        
#>  [5] "bukit timah"                   "changbaishan"                 
#>  [7] "cocoli"                        "danum valley"                 
#>  [9] "dinghushan"                    "doi inthanon"                 
#> [11] "donglingshan"                  "fushan"                       
#> [13] "gutianshan"                    "haliburton"                   
#> [15] "harvard forest"                "heishiding"                   
#> [17] "hong kong"                     "huai kha khaeng"              
#> [19] "ilha do cardoso"               "ituri-edoro1"                 
#> [21] "ituri-edoro2"                  "ituri-lenda1"                 
#> [23] "ituri-lenda2"                  "ituri average (edoro & lenda)"
#> [25] "jianfengling"                  "kenting"                      
#> [27] "khao chong"                    "korup"                        
#> [29] "kuala belalong"                "la planada"                   
#> [31] "lambir"                        "laupahoehoe"                  
#> [33] "lienhuachih"                   "lilly dickey woods"           
#> [35] "luquillo"                      "manaus"                       
#> [37] "mo singto"                     "mpala"                        
#> [39] "mudumalai"                     "nanjenshan"                   
#> [41] "nonggang"                      "palamanui"                    
#> [43] "palanan"                       "pasoh"                        
#> [45] "rabi"                          "san lorenzo/ sherman"         
#> [47] "santa cruz"                    "scbi"                         
#> [49] "scotty creek"                  "serc"                         
#> [51] "sinharaja"                     "speulderbos"                  
#> [53] "tiantongshan"                  "tyson research center"        
#> [55] "wabikon"                       "wanang"                       
#> [57] "wind river"                    "wytham woods"                 
#> [59] "xishuangbanna"                 "yasuni"                       
#> [61] "yosemite national park"        "zenlun"                       
#> [63] "zofin"
```

Created on 2019-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by gonzalezeb** [comment]
It should be good now (sites match in both tables)

question unrelated: I couldn't update data.R because when I call the library (here) R tells me this: 

> In addition: Warning message:
package ‘here’ was built under R version 3.5.3 

but how is that possible if that version was just released? I think I am done for the day!

**Comment by maurolepore** [comment]
Awesome, thanks! Before we call it done, Can you check what's going on with `sites_info`? There is somethig odd with the last columns

![image](https://user-images.githubusercontent.com/5856545/54642404-e5913b80-4a6a-11e9-921f-61a5615342fa.png)

--
.

> when I call the library (here) R tells me this ... how is that possible if that version was just released? I

I guest that since it's latest release (few days ago), R may be (automarically) re-building all packages from the source they store.

I'm not surprised that you get a warning -- I also get warnings because I haven't updated R yet. But I don't see how that would make the package to stop working. Can you show me the error message you get?

**Comment by gonzalezeb** [comment]
- I updated site_info..

- this is teh error I get
> library(here)
Error: package or namespace load failed for ‘here’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘backports’
In addition: Warning message:
package ‘here’ was built under R version 3.5.3 
>

**Comment by maurolepore** [comment]
Thanks! I see the fix and updated the data. I'll close now.

RE your error, I would close all  R sessions except one. From the open R session, restart R (shift + control + F10; or _Session > Restart R_). Then run `install.packages("here")`. If this fails try first `install.packages("backports")`. Best will be to run `update.packages(ask = FALSE)`.
