### ISSUE TITLE
Confirm that dbh_min/max are inclusive

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#83]
(Moving from https://github.com/forestgeo/fgeo.biomass/issues/27#issuecomment-474897852 to make sure I don't forget to ask this.)

@teixeirak 

I'm assuming that the limits imposed by `dbh_min/max` are inclusive (see example below). Is my assumption correct?

``` r
# Inclusive limits
fgeo.biomass:::is_in_range(1, 1, 10)
#> [1] TRUE
fgeo.biomass:::is_in_range(10, 1, 10)
#> [1] TRUE

# Out of bounds
fgeo.biomass:::is_in_range(11, 1, 10)
#> [1] FALSE
fgeo.biomass:::is_in_range(0, 1, 10)
#> [1] FALSE

# Well within the limit
fgeo.biomass:::is_in_range(5, 1, 10)
#> [1] TRUE
```

Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)

**Comment by teixeirak** [comment]
Correct.
