### ISSUE TITLE
Table arrangement and conventions

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#85]
Non-urgent question for @gonzalezeb - Can we move equation_taxa be in the equations table? I recognize that its handy to have in sitespecies, but its also necessary to interpret the equations table, and its a property of the equation.

**Comment by teixeirak** [comment]
More broadly than the comment above, I'm finding the tables difficult to work with, and in some cases I think they may be missing important information. Here's my running list (including modification of the one above):

- [ ] The equations table needs a field to indicate the taxa on which it was developed. This is (partially) given in the sitespecies table (`equation_taxa`), but upon looking at the chojnacky_2014_ugbe equations, I noted that it includes only the taxa to which the species in question belongs and not full information about taxa used in the equation. For example, it (1) doesn't differentiate between "Abies < 0.35 spg" (eq. 4872ed) and Abies≥ 0.35 spg (eq. 74dd65) or (2) give the information that  taxa other than the target taxa were included in the allometry ("Fabaceae/   Juglandaceae, other"; eq. 7f7777). This will be something for Erika to decide on, but here's my recommendation: (1) move `equation_taxa` to the equations table, and modify to indicate when multiple taxa were included (e.g., "Fabaceae/ Juglandaceae"); (2) add a field to equations table `original_equation_name` or such so that equations can be easily matched to those in the original publication (for chojnacky_2014_ugbe, this would be, e.g., "Abies≥ 0.35 spg"); (3) add a field in sitepecies briefly describing the type of trees for which the equation was developed (e.g., "Abies≥ 0.35 spg", ""Fabaceae/   Juglandaceae, other", "Pinus saplings"). The purpose of this field will be for users to be able to evaluate how closely a certain species is matched to an equation without having to merge tables and examine several fields.

**Comment by maurolepore** [comment]
Sorry for jumping in your conversation. Just thought it'd be useful to clarify that the individual tables are a low-level detail that users shouldn't need to know about. They can access all the information with a higher level interface such as the `master()`. 

https://github.com/forestgeo/allodb/issues/78#issuecomment-473403301

![image](https://user-images.githubusercontent.com/5856545/55006008-68f2e580-4fb3-11e9-9ecf-eaf4bf763fc7.png)
