### ISSUE TITLE
Review how to interpret `dbh_min_cm` where equations have `dba`

### ISSUE THREAD

**Issue by maurolepore** [forestgeo/allodb#86]
Follows up on https://github.com/forestgeo/allodb/issues/41#issuecomment-480003361

![image](https://user-images.githubusercontent.com/5856545/55639637-d9f68200-5797-11e9-9a9c-99620064da4d.png)

**Comment by gonzalezeb** [comment]
b is the answer

**Comment by gonzalezeb** [comment]
Closing this issues because now we use Paul et al 2016 equation to calculate basal diameter based on dbh. So in those equations were dba is required we substitute dba by the the following:
dba=1.488+1.195*dbh
