### ISSUE TITLE
Include Conti et al. shrub equations?

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#88]
[Conti et al. 2019, GEB](https://onlinelibrary.wiley.com/doi/pdf/10.1111/geb.12907) may be useful. I haven't assessed it yet.

**Comment by teixeirak** [comment]
This study presents a generic shrub equation based on DBA. Their recommendation for calculating shrub/ small tree biomass differs from what we (ForestGEO) are currently doing.

Steps:
- [ ] carefully read the paper
- [ ] do example calculations using two approaches: (1) assume area preserving to calculate DBA, then apply Conti equation to get whole-individual biomass, (2) apply allometries separately to each stem, then sum to get whole-individual biomass. Compare what these do mathematically.
- [ ] evaluate the two approaches described above against Jim Lutz's biomass allometry data

**Comment by gonzalezeb** [comment]
Equation is included. Test suggested by Krista no completed yet.
