### ISSUE TITLE
structural changes to support R code

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#90]
@gonzalezeb,

Following discussion with @ValentineHerr, it looks like we'll need a few structural changes to the sites_species table:
 
- [x] add min and max DBH over which the equation should be applied (which may or may not match the range over which the equation was developed
- [x] separate genus and species into separate fields
- [ ] ensure strict compliance with the family-genus-species fields (e.g., nothing like "all angiosperms" or [genus][speciesA] or [speciesB]
- [x] when multiple equations need to be summed, list together in one row (together in same cell --but careful with comma separation in .csv file, or across multiple columns)
- [x]  we need a field denoting the variable calculated (e.g., agb, height) 
- [x] we need a field to indicate input variable(s) (e.g., DBH, height)

in the equations table:
- [x] Add units conversion:  include two columns with multiplication factor for input variable and output.

**Comment by gonzalezeb** [comment]
> POINT 3: ensure strict compliance with the family-genus-species fields (e.g., nothing like "all angiosperms" or [genus][speciesA] or [speciesB]

This creates a problem in cases where a site uses words like 'unknown" in genus, or species, or "Unidentified' in family (ex. scbi, traustein). We know we can use a generic equation (as already indicated in the site_species table) but I am not sure how to come around this.

**Comment by teixeirak** [comment]
I'm not sure if I'm fully understanding the problem correctly, but see if this makes sense:

What we discussed earlier is that the R code would search for equations that match on family, genus, and species. If there's no match for species (which will be the case if its "unknown" or "unidentified"), you move up a level and look for matches at genus level (with "any" in species field). And so forth. For cases in which family is unidentified, I'm not sure what to recommend.

**Comment by teixeirak** [comment]
>  Add units conversion: include two columns with multiplication factor for input variable and output.

This is in the equations table, correct? (I noticed that I had it wrong above.)

**Comment by gonzalezeb** [comment]
> > Add units conversion: include two columns with multiplication factor for input variable and output.
> 
> This is in the equations table, correct? (I noticed that I had it wrong above.)

yes, equation table. Please review equation_metadata to see if it make sense.

**Comment by teixeirak** [comment]
> yes, equation table. Please review equation_metadata to see if it make sense.

It generally makes sense. A couple things to ensure clarity/ generality:
- [ ]  change `units_original` --> `output_units_original` and `units_original_convert` --> `output_units_convert`
- [ ] what happens with units conversion when the independent variable is other than dbh? (e.g., dba, height?, wood density?)

**Comment by teixeirak** [comment]
>     * [x]  add min and max DBH over which the equation should be applied (which may or may not match the range over which the equation was developed

I've checked this off because the structure is now good, just needs to be filled in. I opened a new issue for that (#93 )

**Comment by teixeirak** [comment]
> [ ] when multiple equations need to be summed, list together in one row (together in same cell --but careful with comma separation in .csv file, or across multiple columns)

Is it better to have these separated by commas, or should we give the equation? For example, when we want to sum equations c59e03, 96c0af, 529234, is it better for `equation_id` to contain "c59e03, 96c0af, 529234" or "c59e03+96c0af+529234"?  (Also, would the comma separations mess up in a .csv file?) 

This is mainly a question for @ValentineHerr , maybe @cpiponiot

**Comment by teixeirak** [comment]
@gonzalezeb, some feedback on the fields you're adding to the equations table:
- I don't think `ecosystem_type` is very useful, as it's very broad.
- If there's any info about stand structure, it would be useful to include that in the description. In particular, open-grown trees may have very different allometries than those in a forest.
- It would be useful to include climate info (see issue #96 ).
