### ISSUE TITLE
Ensure that design is forward-thinking 

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#92]
From conversation today with Helene, it makes sense to design allo-db for likely future uses, even if we don't currently have the relevant information. For example:
- [x] include date of measurement
- [ ] link and maybe contact to datasets
- [ ] handle shape files for geographic info?

**Comment by gonzalezeb** [comment]
To address this issue, I will add into the equation table the following info, when available:
1. Lat, long, elevation where allometry was developed.
2. Add a short forest description which may guide users on selecting equations.

Date of measurements correspond to date of publication (basically), so no need to look for it.

**Comment by gonzalezeb** [comment]
Actually I am adding date of measurement when available.

**Comment by gonzalezeb** [comment]
allodb is forward thinking..
