### ISSUE TITLE
fill in info in sitespecies table

### ISSUE THREAD

**Issue by teixeirak** [forestgeo/allodb#93]
- [ ] output_variable
- [ ] min_input_variable
- [ ] max_input_variable

**Comment by gonzalezeb** [comment]
closing issue as new columns were added into sitespecies table, also descriptions in metadata


Field | Description | Column_type
-- | -- | --
output_variable | Final variable (and unit) calculated. See Appendix 1 for details. | character
min_input_variable | Recommended minimum value of independent (input) variable (e.g., dbh)   over which the equation should be applied (may or may not match the range   over which the equation was developed) | numeric
max_input_variable | Recommended maximum value of    independent (input) variable (e.g., dbh) over which the equation   should be applied (may or may not match the range over which the equation was   developed) | numeric
