### ISSUE TITLE
Differences between specific and generic equations.

### ISSUE THREAD

**Issue by gonzalezeb** [forestgeo/allodb#95]
@teixeirak 
From a brief test, most species-specific equations give biomass results similar to the generic equations (differences are around 4-5 kg)..
However, for this case: _Prunus_ _serotina,_ the results are very off:

#eq  8aecca, ohio, jenkins---dbh range= 0.3-6 cm----units=cm,gr
dbh=10
10^(1.1981+1.5876*(log10(dbh)))*0.001 -------------> 0.6105201 kg

#eq f08fff  --generic chojnacky  dbh range= 3-64 cm  units=cm, kg

exp(-2.2118+2.4133*log(dbh)) ------------------------->28.36 kg

This is something to discuss.
This relates slightly to issue #72

**Comment by teixeirak** [comment]
Thanks for doing this test-- I've long been thinking that the species-specific equations need to be evaluated against generic equations and/or a set of benchmark expectations to identify bad allometries. In this case eq.#8aecca is clearly off. I'd double check that the equation is correctly transcribed from the original pub, and if it is, I'd throw it out.

**Comment by gonzalezeb** [comment]
Yes, we need to run a general test to evaluate evaluated generic vs. sp specific equations

In this case, the equation was wrong, this is the correct equation:
10^(1.1981+1.5876*(log10(dbh^2)))*0.001

**Comment by teixeirak** [comment]
> Yes, we need to run a general test to evaluate evaluated generic vs. sp specific equations

Agreed. The question is exactly what the test should be. It would be great to get @cpiponiot's input on that.

**Comment by cpiponiot** [comment]
If we have some raw data we can compare the prediction error (RMSE). If we don't, then it's not so straight forward. Absurd results can help eliminate some equations (this can happen for example if the range of the original data was too small and predictions outside this range are completely off). In all other cases, I'd choose the equation obtained with the largest dataset.
