### ISSUE TITLE
Weighting equations instead of choosing one

### ISSUE THREAD

**Issue by cpiponiot** [forestgeo/allodb#96]
Here's an idea we came up with this morning with @teixeirak: 
Instead of describing criteria to choose an allometric equation in particular, why not use all relevant equations (same species, genus, generic equations) and give then a weight that's a function of how much we trust the equation (for example the number of observation it's based on, how far we are from the original location or original climate, from the original dbh range, if it's species-/genus-specific or generic, etc.)

Then the AGB of an individual i would be: 

AGB_i = sum ( f_k (dbh_i) * w_k (dbh_i, dbhrange_k, climate_distance_k, Nobs, etc) ) / sum(w_k)

where k is the equation number, dbhrange is the dbh range of the equation, climate_distance is the n-dimensional distance from the original climate (temperature, precipitation, etc), Nobs is the number of observations

It will probably save us some time, make the process more transparent (once we've defined the weight function) and we'd have continuous equations that reflect all the information that we have. 
We want to discuss it with you @gonzalezeb, maybe tomorrow or next week on Skype?

**Comment by teixeirak** [comment]
@hmullerlandau, it would be great to get your input on this idea.

**Comment by teixeirak** [comment]
Erika (@gonzalezeb) and I had some discussion about this today. We agree that it makes sense, and spent some time discussing how to get at climate distance (or, first, climate for allometry sites). We modified the equations table to include needed info.

**Comment by gonzalezeb** [comment]
Closing this issue because we succeeded!
