### ISSUE TITLE
Taxonomic distance

### ISSUE THREAD

**Issue by gonzalezeb** [forestgeo/allodb#97]
I am writing this as an issue to make sure I understand what we are trying to do.
For the taxonomic distance, we are trying to evaluate how closely related are species from a site to species listed in our equation table, that will help us on weighting (ranking) the equation. 

We may need a look up table (a plant phylogeny tree?) to source? I am not sure.

Please correct if I am wrong @cpiponiot @teixeirak

**Comment by teixeirak** [comment]
Correct.

**Comment by cpiponiot** [comment]
To calculate phylogenetic distances, here are some interesting R packages: 

- [V.PhyloMaker](https://onlinelibrary.wiley.com/doi/10.1111/ecog.04434) for a complete vascular plant phylogeny 

- [ape](https://cran.r-project.org/web/packages/ape/ape.pdf) for creating phylogenetic trees and calculating distances (see the `cophenetic` function)

**Comment by gonzalezeb** [comment]
I think I got it @cpiponiot 

> #install.packages("ape")
#install.packages("brranching")
#install.packages("phytools")
#install.packages("maps")
#install.packages("adephylo")
#install.packages("V.PhyloMaker") --this didn't work
#so install github version
#install.packages("remotes")
remotes::install_github("jinyizju/V.PhyloMaker")
library(maps)
library(phytools)
library(adephylo)
library(ape)
library(brranching)

#Example
#We need to construct a tree to find the evolutionary distance between species
#use function `phylomatic` from package `brranching`
p <- c("Quercus alba","Castanea dentata", "Liriodendron tulipifera", "Abies alba", "Acer rubrum")
tree <- phylomatic(taxa=p, get = 'POST')
plot(tree, no.margin=TRUE)
![image](https://user-images.githubusercontent.com/26872628/70182251-779cab00-16b1-11ea-89bd-99987ea061c8.png)


#but this tree has no edge.lenght (or branch length) therefore we cannot calculate distance
#edge.lenght=a numeric vector giving the lengths of the branches given by edge

> str(tree)
List of 5
 $ edge       : num [1:8, 1:2] 6 7 8 9 9 8 7 6 7 8 ...
 $ Nnode      : int 4
 $ tip.label  : chr [1:5] "quercus_alba" "castanea_dentata" "acer_rubrum" "liriodendron_tulipifera" ...
 $ edge.length: NULL
 $ node.label : chr [1:4] "seedplants" "magnoliales_to_asterales" "" "fagaceae"
 $ attr(*, "class")= chr [1:2] "phylo" "phylomatic"
 $ attr(*, "order")= chr "cladewise"

#so we need to use the function `modified.Grafen(tree, power=2)` from pack `phytools` to compute edge lenghts 
tree<-modified.Grafen(tree, power=2)
node.paths(tree, node)
> str(tree)
List of 5
 $ edge       : num [1:8, 1:2] 6 7 8 9 9 8 7 6 7 8 ...
 $ Nnode      : int 4
 $ tip.label  : chr [1:5] "quercus_alba" "castanea_dentata" "acer_rubrum" "liriodendron_tulipifera" ...
 $ edge.length: num [1:8] 0.36 0.28 0.2 0.12 0.12 0.32 0.6 0.96
 $ node.label : chr [1:4] "seedplants" "magnoliales_to_asterales" "" "fagaceae"
 $ attr(*, "class")= chr [1:2] "phylo" "phylomatic"
 $ attr(*, "order")= chr "cladewise"


#Now use the fuction `cophenetic` from the pack `ape` to calculate pairwise distance 
#or distance between the pairs of tips from a phylogenetic tree using its branch lengths
#dist.nodes does the same but between all nodes, internal and terminal, of the tree

![image](https://user-images.githubusercontent.com/26872628/70182091-2a203e00-16b1-11ea-81ff-f8c1039d2e97.png)
![image](https://user-images.githubusercontent.com/26872628/70182326-a581ef80-16b1-11ea-9780-4d2d3650ca9b.png)



#We can also calculate different set of distances using the function `distTips` fomr the pack `adephylo`
#see the vignette for explanation: https://rdrr.io/cran/adephylo/man/distTips.html
distTips(tree, 1:3)
distTips(tree, 1:3, "nNodes")
distTips(tree, 1:3, "Abouheif")
distTips(tree, 1:3, "sumDD")

![image](https://user-images.githubusercontent.com/26872628/70183283-7b313180-16b3-11ea-84ed-459da23a4024.png)


#and we can plot the tree with distances
plotTree(tree)
edgelabels(round(tree$edge.length,3),cex=0.7)

![image](https://user-images.githubusercontent.com/26872628/70182448-dcf09c00-16b1-11ea-9fe0-2ad82f86e207.png)



#Please use scbi as example and let me know what you think
scbi<-read.csv ("scbi.spptable.csv") #find data [here](https://github.com/SCBI-ForestGEO/SCBI-ForestGEO-Data/blob/master/tree_main_census/data/census-csv-files/scbi.spptable.csv)
scbtree <- phylomatic(taxa=scbi$Latin, get = 'GET')
plot(scbtree, no.margin=TRUE)
str(scbtree)

scbtree<-modified.Grafen(scbtree, power=2)
cophenetic(scbtree)
dist.nodes(scbtree)

plotTree(scbtree)
#labels still need some work
edgelabels(round(scbtree$edge.length,3),cex=0.7)


#also read this: https://github.com/jinyizju/S.PhyloMaker
#for plotting: #http://www.phytools.org/anthrotree/plot/

**Comment by cpiponiot** [comment]
wow nice work @gonzalezeb ! we can use something like cophenetic(tree) in the weighting function
