### ISSUE TITLE
Cannot install allodb from remotes

### ISSUE THREAD

**Issue by gonzalezeb** [forestgeo/allodb#99]
Hi @maurolepore, I have a question that you may be able to answer.

Although allodb is still in a trial stage, I would like to be able to install it, however when I use this line:  
```r
remotes::install_github("forestgeo/allodb")
```

I get this error

```r
ERROR: unable to collate and parse R files for package 'allodb'
* removing 'C:/Users/erikab/Documents/R/win-library/3.6/allodb'
Error: Failed to install 'allodb' from GitHub:
  (converted from warning) installation of package ‘C:/Users/erikab/AppData/Local/Temp/RtmpqyhHPO/filed84338954a5/allodb_0.0.0.9005.tar.gz’ had non-zero exit status
```

**Comment by maurolepore** [comment]
I see the same error:


![image](https://user-images.githubusercontent.com/5856545/69567841-f68e3700-0f7f-11ea-9b48-98d7f60340c2.png)

The error message takes me to line 10 of R/get_biomass.R 

There I see a missing bracket.

![image](https://user-images.githubusercontent.com/5856545/69567942-36edb500-0f80-11ea-8fb0-ec0f8c18ef92.png)

**Comment by gonzalezeb** [comment]
Thanks Mauro!
